CREATE TABLE IF NOT EXISTS CommonSequenceSegment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenantId BIGINT NOT NULL,
    lastOperateUserId BIGINT NOT NULL,
    seqCode VARCHAR(64) NOT NULL UNIQUE,
    seqName VARCHAR(128) NOT NULL,
    nextStartId BIGINT NOT NULL,
    stepSize INT NOT NULL,
    versionNo INT NOT NULL DEFAULT 0,
    remark VARCHAR(255),
    sortnum DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    status INTEGER NOT NULL DEFAULT 1,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE CommonSequenceSegment IS '公共主键号段配置表';
COMMENT ON COLUMN CommonSequenceSegment.id IS '号段配置记录标识';
COMMENT ON COLUMN CommonSequenceSegment.tenantId IS '数据所属租户标识';
COMMENT ON COLUMN CommonSequenceSegment.lastOperateUserId IS '最近操作用户标识';
COMMENT ON COLUMN CommonSequenceSegment.seqCode IS '号段编码';
COMMENT ON COLUMN CommonSequenceSegment.seqName IS '号段中文名称';
COMMENT ON COLUMN CommonSequenceSegment.nextStartId IS '下次分配起始主键';
COMMENT ON COLUMN CommonSequenceSegment.stepSize IS '单次号段长度';
COMMENT ON COLUMN CommonSequenceSegment.versionNo IS '乐观锁版本号';
COMMENT ON COLUMN CommonSequenceSegment.remark IS '号段补充说明';
COMMENT ON COLUMN CommonSequenceSegment.sortnum IS '业务排序值';
COMMENT ON COLUMN CommonSequenceSegment.status IS '逻辑状态标记';
COMMENT ON COLUMN CommonSequenceSegment.createdAt IS '数据创建时间';
COMMENT ON COLUMN CommonSequenceSegment.updatedAt IS '数据更新时间';
