package com.sp.selplat.referencedata.backend.common.config;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.sp.selplat.referencedata.backend.common.persistence.ReferenceDataDatabase;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

/**
 * 使用隔离 H2 文件验证 reference-data 数据在关闭连接并重新初始化后仍然存在。
 * 测试目录由 JUnit 管理，不读写正式 {@code apps/reference-data/db/data}。
 */
class ReferenceDataPersistenceConfigurationTest {

    /**
     * 验证相同文件 URL 第二次打开时保留第一次写入的业务类型。
     *
     * @param temporaryDirectory JUnit 提供的隔离临时目录
     * 执行结果示例：第一次写入 {@code persistence-check}，第二次初始化查询数量仍为 {@code 1}。
     */
    @Test
    void shouldKeepReferenceDataAfterDatabaseIsReopened(@TempDir Path temporaryDirectory) {
        // 隔离文件路径 → 与正式运行相同的 H2 file 和 AUTO_SERVER 模式。
        String databaseUrl = "jdbc:h2:file:"
                + temporaryDirectory.resolve("reference-data-test").toAbsolutePath().normalize()
                + ";MODE=MySQL;AUTO_SERVER=TRUE;DATABASE_TO_UPPER=false";
        ReferenceDataPersistenceConfiguration configuration = new ReferenceDataPersistenceConfiguration();
        // 第一次初始化执行正式 migration 并写入一条测试业务类型。
        ReferenceDataDatabase firstDatabase = configuration.referenceDataDatabase(databaseUrl, "sa", "");
        firstDatabase.jdbcTemplate().update(
                "INSERT INTO ReferenceDataType "
                        + "(projectCode, resourceCode, nameZh, status, sortnum) VALUES (?, ?, ?, ?, ?)",
                "test-project", "persistence-check", "持久化验证", 1, 10);
        // 使用相同 URL 重新初始化 → migration 可重复执行且既有业务记录不被覆盖或删除。
        ReferenceDataDatabase reopenedDatabase = configuration.referenceDataDatabase(databaseUrl, "sa", "");
        Integer persistedCount = reopenedDatabase.jdbcTemplate().queryForObject(
                "SELECT COUNT(*) FROM ReferenceDataType WHERE projectCode = ? AND resourceCode = ?",
                Integer.class,
                "test-project",
                "persistence-check");
        // 第二次数据库上下文仍能读到第一次写入记录，证明文件存储跨重启保留。
        assertEquals(1, persistedCount);
    }

    /**
     * 验证旧数据库升级时保留类型数据，同时移除无效输出形态字段和职责混合的旧空表。
     *
     * @param temporaryDirectory JUnit 提供的隔离临时目录
     * 执行结果示例：旧类型 {@code legacy-project/legacy-type} 保留，数据库只剩
     *     {@code ReferenceDataType} 与 {@code ReferenceDataTreeNode} 两张正式业务表。
     */
    @Test
    void shouldUpgradeLegacySchemaWithoutLosingTypeData(@TempDir Path temporaryDirectory) {
        // 隔离旧库路径 → 模拟已经包含 dataShape 和 ReferenceDataItem 的正式数据库。
        String databaseUrl = "jdbc:h2:file:"
                + temporaryDirectory.resolve("reference-data-legacy-test").toAbsolutePath().normalize()
                + ";MODE=MySQL;AUTO_SERVER=TRUE;DATABASE_TO_UPPER=false";
        DriverManagerDataSource legacyDataSource = new DriverManagerDataSource(databaseUrl, "sa", "");
        legacyDataSource.setDriverClassName("org.h2.Driver");
        JdbcTemplate legacyJdbc = new JdbcTemplate(legacyDataSource);
        // 旧类型结构包含已确认无控制作用的 dataShape 字段，其余列与正式旧库保持一致。
        legacyJdbc.execute("CREATE TABLE ReferenceDataType ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "projectCode VARCHAR(64) NOT NULL, resourceCode VARCHAR(64) NOT NULL, "
                + "nameZh VARCHAR(120) NOT NULL, nameJa VARCHAR(120), nameEn VARCHAR(120), "
                + "descriptionZh VARCHAR(500), descriptionJa VARCHAR(500), descriptionEn VARCHAR(500), "
                + "dataShape VARCHAR(16) NOT NULL DEFAULT 'BOTH', status INTEGER NOT NULL DEFAULT 1, "
                + "sortnum DECIMAL(18, 2) NOT NULL DEFAULT 0, createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + "updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + "CONSTRAINT uk_reference_data_type_coordinate UNIQUE (projectCode, resourceCode), "
                + "CONSTRAINT ck_reference_data_type_shape CHECK (dataShape IN ('TREE', 'OPTIONS', 'BOTH')), "
                + "CONSTRAINT ck_reference_data_type_status CHECK (status IN (0, 1, 2)))");
        // 旧明细表在当前正式库中已经确认没有业务记录，仅保留最小结构用于验证升级清理动作。
        legacyJdbc.execute("CREATE TABLE ReferenceDataItem (id BIGINT PRIMARY KEY)");
        legacyJdbc.update(
                "INSERT INTO ReferenceDataType "
                        + "(projectCode, resourceCode, nameZh, dataShape, status, sortnum) VALUES (?, ?, ?, ?, ?, ?)",
                "legacy-project", "legacy-type", "旧类型", "BOTH", 1, 50);

        // 正式初始化入口 → 执行拆分后的两个 schema 文件和类型数据文件。
        ReferenceDataPersistenceConfiguration configuration = new ReferenceDataPersistenceConfiguration();
        ReferenceDataDatabase upgradedDatabase = configuration.referenceDataDatabase(databaseUrl, "sa", "");
        JdbcTemplate upgradedJdbc = upgradedDatabase.jdbcTemplate();
        // 稳定业务坐标仍存在 → 删除旧字段没有重建或覆盖原类型记录。
        Integer preservedTypeCount = upgradedJdbc.queryForObject(
                "SELECT COUNT(*) FROM ReferenceDataType WHERE projectCode = ? AND resourceCode = ?",
                Integer.class,
                "legacy-project",
                "legacy-type");
        assertEquals(1, preservedTypeCount);
        // 数据库元数据 → dataShape 和旧混合表已移除，新树节点表已建立。
        Integer legacyColumnCount = upgradedJdbc.queryForObject(
                "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS "
                        + "WHERE TABLE_SCHEMA = 'PUBLIC' AND TABLE_NAME = 'ReferenceDataType' AND COLUMN_NAME = 'dataShape'",
                Integer.class);
        Integer legacyTableCount = upgradedJdbc.queryForObject(
                "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES "
                        + "WHERE TABLE_SCHEMA = 'PUBLIC' AND TABLE_NAME = 'ReferenceDataItem'",
                Integer.class);
        Integer treeTableCount = upgradedJdbc.queryForObject(
                "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES "
                        + "WHERE TABLE_SCHEMA = 'PUBLIC' AND TABLE_NAME = 'ReferenceDataTreeNode'",
                Integer.class);
        assertEquals(0, legacyColumnCount);
        assertEquals(0, legacyTableCount);
        assertEquals(1, treeTableCount);
    }
}
