-- UniauthTenant 用于保存统一认证域下的租户主数据，当前本地最小运行主要给管理员账号提供 tenantId 归属。
CREATE TABLE IF NOT EXISTS UniauthTenant (
    -- id 作为租户记录标识，供用户、组织等后续领域表稳定引用。
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- tenantId 记录当前数据归属的租户标识，租户主表自身默认保存本租户主键。
    tenantId BIGINT NOT NULL,
    -- lastOperateUserId 记录最后操作该租户数据的用户标识，便于主表直接回看最近维护责任人。
    lastOperateUserId BIGINT NOT NULL,
    -- tenantCode 保存租户业务编码，便于外部系统识别和切换租户时稳定引用。
    tenantCode VARCHAR(50) NOT NULL UNIQUE,
    -- tenantName 保存租户展示名称，供后台列表、详情和切租户场景直接显示。
    tenantName VARCHAR(200) NOT NULL,
    -- tenantStatus 保存租户业务状态，便于区分启用、停用等租户生命周期状态。
    tenantStatus VARCHAR(30) NOT NULL DEFAULT 'enabled',
    -- contactName 保存默认联系人姓名，便于租户资料和通知场景直接复用。
    contactName VARCHAR(100),
    -- contactEmail 保存联系人邮箱，便于租户通知和资料维护场景使用。
    contactEmail VARCHAR(100),
    -- contactPhone 保存联系人电话，便于控制台展示和人工联系。
    contactPhone VARCHAR(50),
    -- expireAt 保存租户到期时间，供后续续费或停用判断使用。
    expireAt TIMESTAMP,
    -- sortnum 保存手工排序值，便于租户列表按业务顺序稳定展示。
    sortnum DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    -- status 保存逻辑状态，默认 1 表示有效，0 表示删除或停用记录。
    status INTEGER NOT NULL DEFAULT 1,
    -- createdAt 保存创建时间，便于审计初始化和后续新建来源。
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- updatedAt 保存最后更新时间，便于跟踪后续资料变更。
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE UniauthTenant IS '统一认证租户主表';
COMMENT ON COLUMN UniauthTenant.id IS '租户主记录标识';
COMMENT ON COLUMN UniauthTenant.tenantId IS '当前数据归属租户标识';
COMMENT ON COLUMN UniauthTenant.lastOperateUserId IS '最近操作用户标识';
COMMENT ON COLUMN UniauthTenant.tenantCode IS '租户业务编码';
COMMENT ON COLUMN UniauthTenant.tenantName IS '租户展示名称';
COMMENT ON COLUMN UniauthTenant.tenantStatus IS '租户业务状态';
COMMENT ON COLUMN UniauthTenant.contactName IS '默认联系人姓名';
COMMENT ON COLUMN UniauthTenant.contactEmail IS '默认联系人邮箱';
COMMENT ON COLUMN UniauthTenant.contactPhone IS '默认联系人电话';
COMMENT ON COLUMN UniauthTenant.expireAt IS '租户到期时间';
COMMENT ON COLUMN UniauthTenant.sortnum IS '业务排序值';
COMMENT ON COLUMN UniauthTenant.status IS '逻辑状态标记';
COMMENT ON COLUMN UniauthTenant.createdAt IS '数据创建时间';
COMMENT ON COLUMN UniauthTenant.updatedAt IS '数据更新时间';
