-- CommonSequenceSegment 用于保存当前工程按模块缓存主键号段的公共配置。
CREATE TABLE IF NOT EXISTS CommonSequenceSegment (
    -- id 作为号段配置记录标识，供后台维护和后续扩展稳定引用。
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- tenantId 表达当前号段配置归属的租户边界，便于多租户环境下隔离不同租户的主键规则。
    tenantId BIGINT NOT NULL,
    -- lastOperateUserId 记录最近维护该号段配置的用户标识，便于主表直接回看最新维护责任人。
    lastOperateUserId BIGINT NOT NULL,
    -- seqCode 保存模块号段编码，供发号服务按编码快速定位目标配置，要求全局唯一。
    seqCode VARCHAR(64) NOT NULL UNIQUE,
    -- seqName 保存号段中文名称，便于后台配置页面和运维排查时直接识别。
    seqName VARCHAR(128) NOT NULL,
    -- nextStartId 保存下一次成功抢号时可分配的起始主键值。
    nextStartId BIGINT NOT NULL,
    -- stepSize 保存每次成功抢号后分配给单个实例的号段长度。
    stepSize INT NOT NULL,
    -- versionNo 保存乐观锁版本号，供多实例并发抢号时做原子更新控制。
    versionNo INT NOT NULL DEFAULT 0,
    -- remark 保存号段补充说明，便于记录该模块主键策略或特殊约束。
    remark VARCHAR(255),
    -- sortnum 保存配置展示顺序，便于后台配置页按业务顺序稳定展示。
    sortnum DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    -- status 保存逻辑状态，默认 1 表示启用，0 或其他值表示停用或删除。
    status INTEGER NOT NULL DEFAULT 1,
    -- createdAt 保存号段配置创建时间，便于排查初始化来源。
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- updatedAt 保存号段配置最后更新时间，便于确认最近一次维护时间。
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE CommonSequenceSegment IS '公共主键号段配置表';
COMMENT ON COLUMN CommonSequenceSegment.id IS '号段配置记录标识';
COMMENT ON COLUMN CommonSequenceSegment.tenantId IS '数据所属租户标识';
COMMENT ON COLUMN CommonSequenceSegment.lastOperateUserId IS '最近操作用户标识';
COMMENT ON COLUMN CommonSequenceSegment.seqCode IS '号段编码';
COMMENT ON COLUMN CommonSequenceSegment.seqName IS '号段中文名称';
COMMENT ON COLUMN CommonSequenceSegment.nextStartId IS '下次分配起始主键';
COMMENT ON COLUMN CommonSequenceSegment.stepSize IS '单次号段长度';
COMMENT ON COLUMN CommonSequenceSegment.versionNo IS '乐观锁版本号';
COMMENT ON COLUMN CommonSequenceSegment.remark IS '号段补充说明';
COMMENT ON COLUMN CommonSequenceSegment.sortnum IS '业务排序值';
COMMENT ON COLUMN CommonSequenceSegment.status IS '逻辑状态标记';
COMMENT ON COLUMN CommonSequenceSegment.createdAt IS '数据创建时间';
COMMENT ON COLUMN CommonSequenceSegment.updatedAt IS '数据更新时间';
