-- CommonSequenceSegment 保存 reference-data 各业务表独立缓存主键号段的公共配置。
CREATE TABLE IF NOT EXISTS CommonSequenceSegment (
    -- id 仅标识号段配置自身；为避免号段表依赖自己发号，保留数据库自增。
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- tenantId 标识号段配置所属租户，当前平台内置配置统一属于租户 1。
    tenantId BIGINT NOT NULL,
    -- lastOperateUserId 记录最近维护号段配置的用户，当前平台初始化用户为 1。
    lastOperateUserId BIGINT NOT NULL,
    -- seqCode 由实际业务表名加 Id 组成，一张业务表只能对应一个唯一编码。
    seqCode VARCHAR(64) NOT NULL UNIQUE,
    -- seqName 保存管理和排障时可直接识别的中文名称。
    seqName VARCHAR(128) NOT NULL,
    -- nextStartId 保存下一个进程成功抢号时取得的起始主键。
    nextStartId BIGINT NOT NULL,
    -- stepSize 保存单个进程每次缓存的主键数量。
    stepSize INT NOT NULL,
    -- versionNo 作为多进程竞争号段时的乐观锁版本。
    versionNo INT NOT NULL DEFAULT 0,
    -- remark 保存当前号段的主键策略说明。
    remark VARCHAR(255),
    -- sortnum 保存号段管理页面中的稳定顺序。
    sortnum DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    -- status 保存逻辑状态，1 启用、0 停用。
    status INTEGER NOT NULL DEFAULT 1,
    -- createdAt 保存配置首次创建时间。
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- updatedAt 保存配置最近更新时间。
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE CommonSequenceSegment IS 'reference-data公共主键号段配置表';
COMMENT ON COLUMN CommonSequenceSegment.id IS '号段配置记录标识，由数据库自增避免循环发号';
COMMENT ON COLUMN CommonSequenceSegment.tenantId IS '号段配置所属租户标识';
COMMENT ON COLUMN CommonSequenceSegment.lastOperateUserId IS '最近维护号段配置的用户标识';
COMMENT ON COLUMN CommonSequenceSegment.seqCode IS '实际业务表名加Id形成的唯一号段编码';
COMMENT ON COLUMN CommonSequenceSegment.seqName IS '号段中文名称';
COMMENT ON COLUMN CommonSequenceSegment.nextStartId IS '下一次成功抢号的起始主键';
COMMENT ON COLUMN CommonSequenceSegment.stepSize IS '单个进程一次缓存的号段长度';
COMMENT ON COLUMN CommonSequenceSegment.versionNo IS '多进程抢号乐观锁版本';
COMMENT ON COLUMN CommonSequenceSegment.remark IS '号段主键策略说明';
COMMENT ON COLUMN CommonSequenceSegment.sortnum IS '号段配置业务排序值';
COMMENT ON COLUMN CommonSequenceSegment.status IS '逻辑状态：1启用、0停用';
COMMENT ON COLUMN CommonSequenceSegment.createdAt IS '配置创建时间';
COMMENT ON COLUMN CommonSequenceSegment.updatedAt IS '配置更新时间';
