-- ReferenceDataTreeNode 只保存某个引用数据类型下的树节点，并通过 parentId 组织层级关系。
CREATE TABLE IF NOT EXISTS ReferenceDataTreeNode (
    -- id 作为树节点主键，由当前 reference-data 独立数据库生成。
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- typeId 关联所属 ReferenceDataType，所有树节点必须归属于一个明确类型。
    typeId BIGINT NOT NULL,
    -- parentId 关联同表父节点；根节点保持为空。
    parentId BIGINT,
    -- nodeCode 保存类型内部稳定的节点编码，与 typeId 共同保证唯一。
    nodeCode VARCHAR(100) NOT NULL,
    -- nodeValue 保存业务系统实际提交或查询使用的稳定节点值。
    nodeValue VARCHAR(200) NOT NULL,
    -- labelZh 保存节点中文显示文本。
    labelZh VARCHAR(200) NOT NULL,
    -- labelJa 保存节点日文显示文本；未配置时由上层国际化回退策略处理。
    labelJa VARCHAR(200),
    -- labelEn 保存节点英文显示文本；未配置时由上层国际化回退策略处理。
    labelEn VARCHAR(200),
    -- attributesJson 保存节点业务扩展属性 JSON，不承载类型目录中的固定字段。
    attributesJson CLOB,
    -- status 保存逻辑状态：0 表示逻辑删除，1 表示启用，2 表示停用。
    status INTEGER NOT NULL DEFAULT 1,
    -- sortnum 保存同类型或同父节点下的业务排序值。
    sortnum DECIMAL(18, 2) NOT NULL DEFAULT 0,
    -- createdAt 保存树节点首次创建时间。
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- updatedAt 保存树节点最近更新时间。
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 类型外键保证树节点不会脱离类型目录独立存在。
    CONSTRAINT fk_reference_data_tree_node_type FOREIGN KEY (typeId) REFERENCES ReferenceDataType(id),
    -- 父节点外键保证树形关系只能引用当前树节点表中的真实记录。
    CONSTRAINT fk_reference_data_tree_node_parent FOREIGN KEY (parentId) REFERENCES ReferenceDataTreeNode(id),
    -- 同一类型内节点编码不得重复，保证项目按稳定编码读取时只命中一条记录。
    CONSTRAINT uk_reference_data_tree_node_code UNIQUE (typeId, nodeCode),
    -- 状态只接受删除、启用和停用三个生命周期值。
    CONSTRAINT ck_reference_data_tree_node_status CHECK (status IN (0, 1, 2))
);

COMMENT ON TABLE ReferenceDataTreeNode IS '引用数据树节点表';
COMMENT ON COLUMN ReferenceDataTreeNode.id IS '树节点主键，由reference-data独立数据库生成';
COMMENT ON COLUMN ReferenceDataTreeNode.typeId IS '所属引用数据类型主键';
COMMENT ON COLUMN ReferenceDataTreeNode.parentId IS '父树节点主键，根节点为空';
COMMENT ON COLUMN ReferenceDataTreeNode.nodeCode IS '类型内稳定树节点编码';
COMMENT ON COLUMN ReferenceDataTreeNode.nodeValue IS '业务提交和查询使用的稳定节点值';
COMMENT ON COLUMN ReferenceDataTreeNode.labelZh IS '树节点中文显示文本';
COMMENT ON COLUMN ReferenceDataTreeNode.labelJa IS '树节点日文显示文本';
COMMENT ON COLUMN ReferenceDataTreeNode.labelEn IS '树节点英文显示文本';
COMMENT ON COLUMN ReferenceDataTreeNode.attributesJson IS '树节点业务扩展属性JSON';
COMMENT ON COLUMN ReferenceDataTreeNode.status IS '逻辑状态：0删除、1启用、2停用';
COMMENT ON COLUMN ReferenceDataTreeNode.sortnum IS '同类型或同父节点下的业务排序值';
COMMENT ON COLUMN ReferenceDataTreeNode.createdAt IS '数据创建时间';
COMMENT ON COLUMN ReferenceDataTreeNode.updatedAt IS '数据最后更新时间';

-- 树节点按类型、状态和顺序输出时复用该索引。
CREATE INDEX IF NOT EXISTS idx_reference_data_tree_node_type_status_sort
    ON ReferenceDataTreeNode(typeId, status, sortnum, id);

-- 当前正式库已确认旧表没有业务记录；删除职责混合的旧空表，避免后续继续误用树和选项共用结构。
DROP TABLE IF EXISTS ReferenceDataItem;
