import type { AuditLogInfo } from "./audit.js";
import type { DesktopEnvironment, WindowAction, WorkspacePermission } from "./base.js";
import type { AutomaticTestPreflightResult, CodexApproval, CodexHarnessStatus, CodexLoginResponse, CodexModelCatalog, CodexUserInputRequest, ResolveCodexUserInputRequest, TrustedCommandInfo } from "./codex.js";
import type { CodexStreamEvent } from "./codex-stream.js";
import type { CollaborationState, CollaborationStreamEnvelope, CreateCollaborationMemberRequest, DesktopOperatingMode, SubmitCollaborationTaskRequest, UpdateCollaborationMemberRequest } from "./collaboration.js";
import type { CodexSessionInfo, ConversationDispatchState, EnqueueMessageRequest, SendMessageRequest, SendMessageResponse } from "./conversation.js";
import type { AiMemoryDatabaseStatus } from "./database.js";
import type { CreateLinghuStartupPromptRequest, LinghuAutomationState, LinghuAutomationStateEvent, UpdateLinghuStartupPromptRequest } from "./linghu-automation.js";
import type { ConvertNangongConversationToTopicRequest, CreateEvolutionProposalRequest, CreateEvolutionTopicRequest, CreateLinghuRepairProposalRequest, DecideEvolutionProposalRequest, GenerateNangongTopicDraftRequest, NangongEvolutionState, NangongEvolutionStateEvent, NangongTopicDraft, ReviseEvolutionProposalRequest, SendNangongConversationMessageRequest, UpdateEvolutionTopicRequest } from "./nangong-evolution.js";
import type { DesktopSettings } from "./settings.js";
import type { ScreenCapture, ScreenCaptureFrameRequest, ScreenCaptureFrameResult, ScreenCapturePreparationResult, ScreenCaptureRequest, ScreenshotAnnotationWindowRequest, ScreenshotAttachment, ScreenshotCompletedEvent, ScreenshotSaveRequest, TempDirectoryInfo } from "./screenshot.js";
import type { WorkspaceEntry, WorkspaceState } from "./workspace.js";

/** 定义 preload 向渲染层公开的完整白名单；各领域数据结构保留在独立契约文件。 */
export interface DesktopApi {
  getEnvironment(): Promise<DesktopEnvironment>;
  getAiMemoryDatabaseStatus(): Promise<AiMemoryDatabaseStatus>;
  getSettings(): Promise<DesktopSettings>;
  updateSettings(settings: Partial<DesktopSettings>): Promise<DesktopSettings>;
  getWorkspaces(): Promise<WorkspaceState>;
  addWorkspace(): Promise<WorkspaceState>;
  updateWorkspacePermission(id: string, permission: WorkspacePermission): Promise<WorkspaceState>;
  setPrimaryWorkspace(id: string): Promise<WorkspaceState>;
  removeWorkspace(id: string): Promise<WorkspaceState>;
  listWorkspaceEntries(id: string): Promise<WorkspaceEntry[]>;
  getCodexStatus(): Promise<CodexHarnessStatus>;
  getCodexModels(): Promise<CodexModelCatalog>;
  getActiveCodexSession(): Promise<CodexSessionInfo>;
  loginWithChatGPT(): Promise<CodexLoginResponse>;
  logoutCodex(): Promise<CodexHarnessStatus>;
  getCodexApprovals(): Promise<CodexApproval[]>;
  resolveCodexApproval(requestId: number, decision: "accept" | "decline"): Promise<void>;
  getTrustedCommandInfo(): Promise<TrustedCommandInfo>;
  clearTrustedCommands(): Promise<TrustedCommandInfo>;
  prepareAutomaticTesting(): Promise<AutomaticTestPreflightResult>;
  getCodexUserInputs(): Promise<CodexUserInputRequest[]>;
  resolveCodexUserInput(request: ResolveCodexUserInputRequest): Promise<void>;
  newChat(): Promise<void>;
  openExternalUrl(url: string): Promise<void>;
  prepareScreenCapture(): Promise<ScreenCapturePreparationResult>;
  openScreenRecordingSettings(): Promise<void>;
  restartForScreenRecordingPermission(): Promise<void>;
  captureScreen(request?: ScreenCaptureRequest): Promise<ScreenCapture | null>;
  notifyScreenCaptureStage(stage: string, detail?: string): Promise<void>;
  onScreenCaptureFrameRequested(listener: (request: ScreenCaptureFrameRequest) => void): () => void;
  submitScreenCaptureFrameResult(result: ScreenCaptureFrameResult): Promise<void>;
  showScreenshotWindow(): Promise<void>;
  onScreenCaptureReset(listener: () => void): () => void;
  enterScreenshotAnnotation(request: ScreenshotAnnotationWindowRequest): Promise<void>;
  returnScreenshotSelection(): Promise<void>;
  endScreenshotEditing(): Promise<void>;
  saveScreenshot(request: ScreenshotSaveRequest): Promise<ScreenshotAttachment>;
  onScreenshotCompleted(listener: (event: ScreenshotCompletedEvent) => void): () => void;
  getTempDirectoryInfo(): Promise<TempDirectoryInfo>;
  openTempDirectory(): Promise<void>;
  clearTempFiles(): Promise<TempDirectoryInfo>;
  getAuditLogInfo(): Promise<AuditLogInfo>;
  openAuditLogDirectory(): Promise<void>;
  getCollaborationState(): Promise<CollaborationState>;
  setDesktopOperatingMode(mode: DesktopOperatingMode): Promise<CollaborationState>;
  selectCollaborationMember(memberId: string): Promise<CollaborationState>;
  createCollaborationMember(request: CreateCollaborationMemberRequest): Promise<CollaborationState>;
  updateCollaborationMember(memberId: string, request: UpdateCollaborationMemberRequest): Promise<CollaborationState>;
  deleteCollaborationMember(memberId: string): Promise<CollaborationState>;
  submitCollaborationTask(request: SubmitCollaborationTaskRequest): Promise<CollaborationState>;
  continueCollaborationTask(taskId: string): Promise<CollaborationState>;
  cancelCollaborationTask(taskId: string): Promise<CollaborationState>;
  onCollaborationState(listener: (event: import("./collaboration.js").CollaborationStateEvent) => void): () => void;
  onCollaborationStream(listener: (event: CollaborationStreamEnvelope) => void): () => void;
  getLinghuAutomationState(): Promise<LinghuAutomationState>;
  setLinghuAutomationEnabled(enabled: boolean): Promise<LinghuAutomationState>;
  createLinghuStartupPrompt(request: CreateLinghuStartupPromptRequest): Promise<LinghuAutomationState>;
  updateLinghuStartupPrompt(promptId: string, request: UpdateLinghuStartupPromptRequest): Promise<LinghuAutomationState>;
  deleteLinghuStartupPrompt(promptId: string): Promise<LinghuAutomationState>;
  selectLinghuStartupPrompt(promptId: string): Promise<LinghuAutomationState>;
  onLinghuAutomationState(listener: (event: LinghuAutomationStateEvent) => void): () => void;
  getNangongEvolutionState(): Promise<NangongEvolutionState>;
  createEvolutionTopic(request: CreateEvolutionTopicRequest): Promise<NangongEvolutionState>;
  setNangongAutomation(kind: "evolution" | "nangong-approval" | "linghu-approval" | "execution", enabled: boolean): Promise<NangongEvolutionState>;
  sendNangongConversationMessage(request: SendNangongConversationMessageRequest): Promise<NangongEvolutionState>;
  newNangongConversation(): Promise<NangongEvolutionState>;
  generateNangongTopicDraft(request: GenerateNangongTopicDraftRequest): Promise<NangongTopicDraft>;
  convertNangongConversationToTopic(request: ConvertNangongConversationToTopicRequest): Promise<NangongEvolutionState>;
  createEvolutionProposal(topicId: string, request: CreateEvolutionProposalRequest): Promise<NangongEvolutionState>;
  updateEvolutionTopic(topicId: string, request: UpdateEvolutionTopicRequest): Promise<NangongEvolutionState>;
  createLinghuRepairProposal(request: CreateLinghuRepairProposalRequest): Promise<NangongEvolutionState>;
  decideEvolutionProposal(proposalId: string, request: DecideEvolutionProposalRequest): Promise<NangongEvolutionState>;
  reviseEvolutionProposal(proposalId: string, request: ReviseEvolutionProposalRequest): Promise<NangongEvolutionState>;
  autoApproveEvolutionProposal(proposalId: string): Promise<NangongEvolutionState>;
  dispatchEvolutionProposal(proposalId: string): Promise<NangongEvolutionState>;
  onNangongEvolutionState(listener: (event: NangongEvolutionStateEvent) => void): () => void;
  getConversationDispatchState(): Promise<ConversationDispatchState>;
  enqueueMessage(request: EnqueueMessageRequest): Promise<ConversationDispatchState>;
  supplementQueuedMessage(itemId: string): Promise<ConversationDispatchState>;
  discardQueuedMessage(itemId: string): Promise<ConversationDispatchState>;
  recoverConversationTask(): Promise<ConversationDispatchState>;
  discardConversationRecovery(): Promise<ConversationDispatchState>;
  onConversationDispatchState(listener: (state: ConversationDispatchState) => void): () => void;
  sendMessage(request: SendMessageRequest): Promise<SendMessageResponse>;
  onCodexStreamEvent(listener: (event: CodexStreamEvent) => void): () => void;
  cancel(): Promise<boolean>;
  windowControl(action: WindowAction): void;
}
