/** 协同、令狐自动化与南宫演化桥接；领域命令只传递结构化数据。 */
import { invoke, subscribe } from "../ipc-client.cjs";

export function collaborationBridge() {
  return {
    getCollaborationState: () => invoke("desktop:get-collaboration-state"),
    getCollaborationTimeline: () => invoke("desktop:get-collaboration-timeline"),
    onCollaborationTimelineChanged: (listener: (event: unknown) => void) => subscribe("desktop:collaboration-timeline-changed", listener),
    setDesktopOperatingMode: (mode: string) => invoke("desktop:set-operating-mode", mode),
    selectCollaborationMember: (memberId: string) => invoke("desktop:select-collaboration-member", memberId),
    createCollaborationMember: (request: unknown) => invoke("desktop:create-collaboration-member", request),
    updateCollaborationMember: (memberId: string, request: unknown) => invoke("desktop:update-collaboration-member", memberId, request),
    deleteCollaborationMember: (memberId: string) => invoke("desktop:delete-collaboration-member", memberId),
    submitCollaborationTask: (request: unknown) => invoke("desktop:submit-collaboration-task", request),
    continueCollaborationTask: (taskId: string) => invoke("desktop:continue-collaboration-task", taskId),
    cancelCollaborationTask: (taskId: string) => invoke("desktop:cancel-collaboration-task", taskId),
    onCollaborationState: (listener: (event: unknown) => void) => subscribe("desktop:collaboration-state", listener),
    onCollaborationStream: (listener: (event: unknown) => void) => subscribe("desktop:collaboration-stream", listener),
    getLinghuAutomationState: () => invoke("desktop:get-linghu-automation-state"),
    setLinghuAutomationEnabled: (enabled: boolean) => invoke("desktop:set-linghu-automation-enabled", enabled),
    createLinghuStartupPrompt: (request: unknown) => invoke("desktop:create-linghu-startup-prompt", request),
    updateLinghuStartupPrompt: (promptId: string, request: unknown) => invoke("desktop:update-linghu-startup-prompt", promptId, request),
    deleteLinghuStartupPrompt: (promptId: string) => invoke("desktop:delete-linghu-startup-prompt", promptId),
    selectLinghuStartupPrompt: (promptId: string) => invoke("desktop:select-linghu-startup-prompt", promptId),
    onLinghuAutomationState: (listener: (event: unknown) => void) => subscribe("desktop:linghu-automation-state", listener),
    getEvolutionState: () => invoke("desktop:get-nangong-evolution-state"),
    openEvolutionWorkspace: (location: unknown) => invoke("desktop:open-evolution-workspace", location),
    onEvolutionWorkspaceLocation: (listener: (location: unknown) => void) => subscribe("desktop:evolution-workspace-location", listener),
    getEvolutionTopicDossier: (topicId: string) => invoke("desktop:get-evolution-topic-dossier", topicId),
    queryEvolutionWorkbench: (request: unknown) => invoke("desktop:query-evolution-workbench", request),
    getEvolutionWorkbenchPreference: (perspective: unknown, nodeId: unknown) => invoke("desktop:get-evolution-workbench-preference", perspective, nodeId),
    saveEvolutionWorkbenchPreference: (request: unknown) => invoke("desktop:save-evolution-workbench-preference", request),
    onEvolutionWorkbenchChanged: (listener: (event: unknown) => void) => subscribe("desktop:evolution-workbench-changed", listener),
    // 页面只传人物 ID；增加新人物时 preload 不需要再增加方法。
    getPersonaConversation: (personaId: string) => invoke("desktop:get-persona-conversation", personaId),
    sendPersonaConversationMessage: (personaId: string, request: unknown) => invoke("desktop:send-persona-conversation-message", personaId, request),
    newPersonaConversation: (personaId: string) => invoke("desktop:new-persona-conversation", personaId),
    generateNangongTopicDraft: (request: unknown) => invoke("desktop:generate-nangong-topic-draft", request),
    convertNangongConversationToTopic: (request: unknown) => invoke("desktop:convert-nangong-conversation-to-topic", request),
    createEvolutionTopic: (request: unknown) => invoke("desktop:create-evolution-topic", request),
    updateEvolutionTopic: (topicId: string, request: unknown) => invoke("desktop:update-evolution-topic", topicId, request),
    setEvolutionAutomationEnabled: (kind: string, enabled: boolean) => invoke("desktop:set-nangong-automation", kind, enabled),
    configureEvolutionAutomation: (request: unknown) => invoke("desktop:configure-evolution-automation", request),
    controlEvolutionAutomation: (action: string) => invoke("desktop:control-evolution-automation", action),
    resumeEvolutionOneShot: () => invoke("desktop:resume-nangong-one-shot-evolution"),
    createEvolutionProposal: (topicId: string, request: unknown) => invoke("desktop:create-evolution-proposal", topicId, request),
    createLinghuRepairProposal: (request: unknown) => invoke("desktop:create-linghu-repair-proposal", request),
    decideEvolutionProposal: (proposalId: string, request: unknown) => invoke("desktop:decide-evolution-proposal", proposalId, request),
    decideEvolutionResult: (proposalId: string, request: unknown) => invoke("desktop:decide-evolution-result", proposalId, request),
    generateHanLiAcceptancePlan: (proposalId: string) => invoke("desktop:generate-han-li-acceptance-plan", proposalId),
    executeHanLiAcceptancePlan: (planId: string) => invoke("desktop:execute-han-li-acceptance-plan", planId),
    reviseEvolutionProposal: (proposalId: string, request: unknown) => invoke("desktop:revise-evolution-proposal", proposalId, request),
    autoApproveEvolutionProposal: (proposalId: string, request: unknown) => invoke("desktop:auto-approve-evolution-proposal", proposalId, request),
    dispatchEvolutionProposal: (proposalId: string, request: unknown) => invoke("desktop:dispatch-evolution-proposal", proposalId, request),
    onEvolutionState: (listener: (event: unknown) => void) => subscribe("desktop:evolution-state", listener),
  };
}
