-- 角色根和两类角色目录先插入，后续角色以 parentId 形成一张表的完整树。
INSERT INTO AiRole(id,parentId,roleCode,roleName,roleType,experienceLevel,codexPoolType,specialty,status,sortnum)
SELECT 100000,NULL,'ROLE_ROOT','角色类型','ENGINEER','INEXPERIENCED','DISPOSABLE',NULL,1,0
WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='ROLE_ROOT');
INSERT INTO AiRole SELECT 100001,100000,'ENGINEER_ROOT','工程师','ENGINEER','INEXPERIENCED','DISPOSABLE',NULL,1,10,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='ENGINEER_ROOT');
INSERT INTO AiRole SELECT 100002,100000,'REVIEWER_ROOT','审核员','REVIEWER','EXPERIENCED','PERSISTENT',NULL,1,20,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='REVIEWER_ROOT');

-- 三个树结构节点属于固定分类，不允许普通角色编辑和排序覆盖其名称、类型或位置。
UPDATE AiRole SET parentId=NULL,roleName='角色类型',roleType='ENGINEER',experienceLevel='INEXPERIENCED',codexPoolType='DISPOSABLE',specialty=NULL,status=1,sortnum=0 WHERE roleCode='ROLE_ROOT';
UPDATE AiRole SET parentId=100000,roleName='工程师',roleType='ENGINEER',experienceLevel='INEXPERIENCED',codexPoolType='DISPOSABLE',specialty=NULL,status=1,sortnum=10 WHERE roleCode='ENGINEER_ROOT';
UPDATE AiRole SET parentId=100000,roleName='审核员',roleType='REVIEWER',experienceLevel='EXPERIENCED',codexPoolType='PERSISTENT',specialty=NULL,status=1,sortnum=20 WHERE roleCode='REVIEWER_ROOT';
-- 普通角色的父分类由 roleType 唯一决定，修复历史编辑只改类型但未移动树节点造成的错挂。
UPDATE AiRole SET parentId=100001 WHERE roleCode NOT IN ('ROLE_ROOT','ENGINEER_ROOT','REVIEWER_ROOT') AND roleType='ENGINEER';
UPDATE AiRole SET parentId=100002 WHERE roleCode NOT IN ('ROLE_ROOT','ENGINEER_ROOT','REVIEWER_ROOT') AND roleType='REVIEWER';

-- 角色体系固定为三个工程角色、三个对应审核员和一个项目经理；历史普通角色只逻辑停用。
UPDATE AiRole SET status=0,updatedAt=CURRENT_TIMESTAMP
WHERE roleCode NOT IN ('ROLE_ROOT','ENGINEER_ROOT','REVIEWER_ROOT','REQUIREMENT_ANALYST','SOFTWARE_ENGINEER',
    'TEST_ENGINEER','REQUIREMENT_REVIEWER','SOFTWARE_REVIEWER','TEST_QUALITY_REVIEWER','PROJECT_MANAGER');

INSERT INTO AiRole SELECT 100010,100001,'REQUIREMENT_ANALYST','需求分析师','ENGINEER','INEXPERIENCED','DISPOSABLE','需求',1,10,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='REQUIREMENT_ANALYST');
INSERT INTO AiRole SELECT 100016,100001,'TEST_ENGINEER','测试工程师','ENGINEER','INEXPERIENCED','DISPOSABLE','测试',1,30,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='TEST_ENGINEER');

-- V2 快速开发流程使用三个固定角色；软件工程师使用新主键，避免覆盖被历史运行引用的代码工程师。
INSERT INTO AiRole SELECT 100027,100001,'SOFTWARE_ENGINEER','软件工程师','ENGINEER','INEXPERIENCED','DISPOSABLE','UI,Python,Java',1,20,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='SOFTWARE_ENGINEER');

-- 三个审核员分别对应需求、软件和测试质量；项目经理独立承担总控职责。
INSERT INTO AiRole SELECT 100028,100002,'REQUIREMENT_REVIEWER','需求审核员','REVIEWER','EXPERIENCED','PERSISTENT','需求质量',1,40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='REQUIREMENT_REVIEWER');
INSERT INTO AiRole SELECT 100029,100002,'SOFTWARE_REVIEWER','软件审核员','REVIEWER','EXPERIENCED','PERSISTENT','软件质量',1,50,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='SOFTWARE_REVIEWER');
INSERT INTO AiRole SELECT 100030,100002,'TEST_QUALITY_REVIEWER','测试审核员','REVIEWER','EXPERIENCED','PERSISTENT','测试质量',1,60,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='TEST_QUALITY_REVIEWER');
INSERT INTO AiRole SELECT 100031,100002,'PROJECT_MANAGER','项目经理','REVIEWER','EXPERIENCED','PERSISTENT','项目总控',1,70,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='PROJECT_MANAGER');

-- 七个固定业务角色每次初始化都恢复为启用状态和稳定顺序，历史逻辑删除不会覆盖本轮角色体系。
UPDATE AiRole SET status=1,sortnum=10,updatedAt=CURRENT_TIMESTAMP WHERE roleCode='REQUIREMENT_ANALYST';
UPDATE AiRole SET status=1,sortnum=20,updatedAt=CURRENT_TIMESTAMP WHERE roleCode='SOFTWARE_ENGINEER';
UPDATE AiRole SET status=1,sortnum=30,updatedAt=CURRENT_TIMESTAMP WHERE roleCode='TEST_ENGINEER';
UPDATE AiRole SET status=1,sortnum=40,updatedAt=CURRENT_TIMESTAMP WHERE roleCode='REQUIREMENT_REVIEWER';
UPDATE AiRole SET status=1,sortnum=50,updatedAt=CURRENT_TIMESTAMP WHERE roleCode='SOFTWARE_REVIEWER';
UPDATE AiRole SET status=1,sortnum=60,updatedAt=CURRENT_TIMESTAMP WHERE roleCode='TEST_QUALITY_REVIEWER';
UPDATE AiRole SET status=1,sortnum=70,updatedAt=CURRENT_TIMESTAMP WHERE roleCode='PROJECT_MANAGER';
