-- 角色根和两类角色目录先插入，后续角色以 parentId 形成一张表的完整树。
INSERT INTO AiRole(id,parentId,roleCode,roleName,roleType,experienceLevel,codexPoolType,specialty,status,sortnum)
SELECT 100000,NULL,'ROLE_ROOT','角色管理','ENGINEER','INEXPERIENCED','DISPOSABLE',NULL,1,0
WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='ROLE_ROOT');
INSERT INTO AiRole SELECT 100001,100000,'ENGINEER_ROOT','工程师','ENGINEER','INEXPERIENCED','DISPOSABLE',NULL,1,10,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='ENGINEER_ROOT');
INSERT INTO AiRole SELECT 100002,100000,'REVIEWER_ROOT','审核员','REVIEWER','EXPERIENCED','PERSISTENT',NULL,1,20,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='REVIEWER_ROOT');

INSERT INTO AiRole SELECT 100010,100001,'REQUIREMENT_ANALYST','需求分析师','ENGINEER','INEXPERIENCED','DISPOSABLE','需求',1,10,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='REQUIREMENT_ANALYST');
INSERT INTO AiRole SELECT 100011,100001,'ARCHITECT','架构师','ENGINEER','EXPERIENCED','PERSISTENT','架构',1,20,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='ARCHITECT');
INSERT INTO AiRole SELECT 100012,100001,'REQUIREMENT_DEFINITION_ENGINEER','要件定义师','ENGINEER','INEXPERIENCED','DISPOSABLE','要件定义',1,30,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='REQUIREMENT_DEFINITION_ENGINEER');
INSERT INTO AiRole SELECT 100013,100001,'DATABASE_ENGINEER','数据库工程师','ENGINEER','EXPERIENCED','PERSISTENT','数据库',1,40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='DATABASE_ENGINEER');
INSERT INTO AiRole SELECT 100014,100001,'DETAIL_DESIGN_ENGINEER','详细设计工程师','ENGINEER','INEXPERIENCED','DISPOSABLE','详细设计',1,50,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='DETAIL_DESIGN_ENGINEER');
INSERT INTO AiRole SELECT 100015,100001,'CODE_ENGINEER','代码工程师','ENGINEER','INEXPERIENCED','DISPOSABLE','UI,Python,Java',1,60,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='CODE_ENGINEER');
INSERT INTO AiRole SELECT 100016,100001,'TEST_ENGINEER','测试工程师','ENGINEER','INEXPERIENCED','DISPOSABLE','测试',1,70,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='TEST_ENGINEER');
INSERT INTO AiRole SELECT 100017,100001,'AI_CUSTOMER_USER','AI客户使用','ENGINEER','EXPERIENCED','PERSISTENT','客户协作',1,80,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='AI_CUSTOMER_USER');
INSERT INTO AiRole SELECT 100018,100001,'DATA_REPAIR_ENGINEER','数据修复师','ENGINEER','EXPERIENCED','PERSISTENT','数据修复',1,90,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='DATA_REPAIR_ENGINEER');
INSERT INTO AiRole SELECT 100019,100001,'IMPLEMENTATION_ROLE','实现工程师','ENGINEER','INEXPERIENCED','DISPOSABLE','通用实现',1,100,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='IMPLEMENTATION_ROLE');

INSERT INTO AiRole SELECT 100020,100002,'REQUIREMENT_QUALITY_REVIEWER','需求质量审核员','REVIEWER','EXPERIENCED','PERSISTENT','需求质量',1,10,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='REQUIREMENT_QUALITY_REVIEWER');
INSERT INTO AiRole SELECT 100021,100002,'ARCHITECTURE_QUALITY_GATE','架构质量门禁','REVIEWER','EXPERIENCED','PERSISTENT','架构质量',1,20,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='ARCHITECTURE_QUALITY_GATE');
INSERT INTO AiRole SELECT 100022,100002,'REQUIREMENT_DEFINITION_GATE','要件定义门禁','REVIEWER','EXPERIENCED','PERSISTENT','要件质量',1,30,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='REQUIREMENT_DEFINITION_GATE');
INSERT INTO AiRole SELECT 100023,100002,'DATABASE_QUALITY_GATE','数据库质量门禁','REVIEWER','EXPERIENCED','PERSISTENT','数据库质量',1,40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='DATABASE_QUALITY_GATE');
INSERT INTO AiRole SELECT 100024,100002,'DETAIL_DESIGN_GATE','详细设计门禁','REVIEWER','EXPERIENCED','PERSISTENT','详细设计质量',1,50,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='DETAIL_DESIGN_GATE');
INSERT INTO AiRole SELECT 100025,100002,'CODE_REVIEWER','代码审核','REVIEWER','EXPERIENCED','PERSISTENT','UI,Python,Java',1,60,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='CODE_REVIEWER');
INSERT INTO AiRole SELECT 100026,100002,'TEST_REVIEWER','测试审核','REVIEWER','EXPERIENCED','PERSISTENT','测试质量',1,70,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='TEST_REVIEWER');
