-- 角色根和两类角色目录先插入，后续角色以 parentId 形成一张表的完整树。
INSERT INTO AiRole(id,parentId,roleCode,roleName,roleType,experienceLevel,codexPoolType,specialty,status,sortnum)
SELECT 100000,NULL,'ROLE_ROOT','角色类型','ENGINEER','INEXPERIENCED','DISPOSABLE',NULL,1,0
WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='ROLE_ROOT');
INSERT INTO AiRole SELECT 100001,100000,'ENGINEER_ROOT','工程师','ENGINEER','INEXPERIENCED','DISPOSABLE',NULL,1,10,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='ENGINEER_ROOT');
INSERT INTO AiRole SELECT 100002,100000,'REVIEWER_ROOT','审核员','REVIEWER','EXPERIENCED','PERSISTENT',NULL,1,20,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='REVIEWER_ROOT');

-- 三个树结构节点属于固定分类，不允许普通角色编辑和排序覆盖其名称、类型或位置。
UPDATE AiRole SET parentId=NULL,roleName='角色类型',roleType='ENGINEER',experienceLevel='INEXPERIENCED',codexPoolType='DISPOSABLE',specialty=NULL,status=1,sortnum=0 WHERE roleCode='ROLE_ROOT';
UPDATE AiRole SET parentId=100000,roleName='工程师',roleType='ENGINEER',experienceLevel='INEXPERIENCED',codexPoolType='DISPOSABLE',specialty=NULL,status=1,sortnum=10 WHERE roleCode='ENGINEER_ROOT';
UPDATE AiRole SET parentId=100000,roleName='审核员',roleType='REVIEWER',experienceLevel='EXPERIENCED',codexPoolType='PERSISTENT',specialty=NULL,status=1,sortnum=20 WHERE roleCode='REVIEWER_ROOT';
-- 普通角色的父分类由 roleType 唯一决定，修复历史编辑只改类型但未移动树节点造成的错挂。
UPDATE AiRole SET parentId=100001 WHERE roleCode NOT IN ('ROLE_ROOT','ENGINEER_ROOT','REVIEWER_ROOT') AND roleType='ENGINEER';
UPDATE AiRole SET parentId=100002 WHERE roleCode NOT IN ('ROLE_ROOT','ENGINEER_ROOT','REVIEWER_ROOT') AND roleType='REVIEWER';

INSERT INTO AiRole SELECT 100010,100001,'REQUIREMENT_ANALYST','需求分析师','ENGINEER','INEXPERIENCED','DISPOSABLE','需求',1,10,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='REQUIREMENT_ANALYST');
INSERT INTO AiRole SELECT 100016,100001,'TEST_ENGINEER','测试工程师','ENGINEER','INEXPERIENCED','DISPOSABLE','测试',1,70,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='TEST_ENGINEER');

-- V2 快速开发流程使用三个固定角色；软件工程师使用新主键，避免覆盖被历史运行引用的代码工程师。
INSERT INTO AiRole SELECT 100015,100001,'SOFTWARE_ENGINEER','软件工程师','ENGINEER','INEXPERIENCED','DISPOSABLE','UI,Python,Java',1,20,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiRole WHERE roleCode='SOFTWARE_ENGINEER');
