-- V2 唯一门禁类型为 AI，按快速开发链保留三个职责。
INSERT INTO AiGate SELECT 110010,130001,'REQUIREMENT_CHECKER','需求检测员','AI_GATE','检查需求是否完整、明确且可开发',1,10,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiGate WHERE projectId=130001 AND gateCode='REQUIREMENT_CHECKER');
INSERT INTO AiGate SELECT 110011,130001,'CODE_CHECKER','代码检测员','AI_GATE','检查代码实现与需求、规范和测试结果',1,20,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiGate WHERE projectId=130001 AND gateCode='CODE_CHECKER');
INSERT INTO AiGate SELECT 110012,130001,'PROJECT_MANAGER_CONTROL','项目经理总控','AI_GATE','汇总项目状态、异常和交付结果',1,30,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM AiGate WHERE projectId=130001 AND gateCode='PROJECT_MANAGER_CONTROL');
