-- ai_agent_registration 保存 Java 登记、由本地 Python 解析并启动的 Agent 地址。
CREATE TABLE IF NOT EXISTS ai_agent_registration (
  -- id 是 Agent 登记记录主键。
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, agent_id VARCHAR(100) NOT NULL,
  version VARCHAR(30) NOT NULL, display_name VARCHAR(200) NOT NULL, endpoint_type VARCHAR(30) NOT NULL,
  endpoint VARCHAR(500) NOT NULL, protocol_version VARCHAR(30) NOT NULL, capabilities_json CLOB NOT NULL,
  config_digest VARCHAR(128) NOT NULL, status VARCHAR(20) NOT NULL,
  CONSTRAINT uk_ai_agent_registration UNIQUE(agent_id, version)
);

COMMENT ON TABLE ai_agent_registration IS 'AI工厂Agent地址与能力版本登记表';
COMMENT ON COLUMN ai_agent_registration.id IS 'Agent登记记录主键';
COMMENT ON COLUMN ai_agent_registration.agent_id IS 'Agent稳定标识';
COMMENT ON COLUMN ai_agent_registration.version IS 'Agent登记版本';
COMMENT ON COLUMN ai_agent_registration.display_name IS 'Agent显示名称';
COMMENT ON COLUMN ai_agent_registration.endpoint_type IS 'Agent端点类型，例如HTTP或本地进程';
COMMENT ON COLUMN ai_agent_registration.endpoint IS 'Python启动Agent时访问的端点地址';
COMMENT ON COLUMN ai_agent_registration.protocol_version IS 'Agent通信协议版本';
COMMENT ON COLUMN ai_agent_registration.capabilities_json IS 'Agent能力清单JSON';
COMMENT ON COLUMN ai_agent_registration.config_digest IS 'Agent配置内容摘要';
COMMENT ON COLUMN ai_agent_registration.status IS 'Agent登记状态';
