-- ai_audit_event 保存 Java 服务端亲自观察到且已脱敏的 HTTP 尝试事实。
CREATE TABLE IF NOT EXISTS ai_audit_event (
  -- id 是服务端审计事件记录主键。
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_code VARCHAR(100) NOT NULL,
  task_id BIGINT, run_id BIGINT, actor_type VARCHAR(40) NOT NULL, actor_id VARCHAR(100) NOT NULL,
  action VARCHAR(100) NOT NULL, target_type VARCHAR(40), target_id VARCHAR(100), attempt_status VARCHAR(30) NOT NULL,
  previous_hash VARCHAR(128) NOT NULL, event_hash VARCHAR(128) NOT NULL, payload_json CLOB, created_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_ai_audit_event_code UNIQUE(event_code)
);
CREATE INDEX IF NOT EXISTS idx_ai_audit_task_time ON ai_audit_event(task_id,created_at);

COMMENT ON TABLE ai_audit_event IS 'Java服务端观察到的脱敏HTTP尝试审计事件表';
COMMENT ON COLUMN ai_audit_event.id IS '服务端审计事件记录主键';
COMMENT ON COLUMN ai_audit_event.event_code IS '审计事件唯一业务编码';
COMMENT ON COLUMN ai_audit_event.task_id IS '审计事件关联任务主键';
COMMENT ON COLUMN ai_audit_event.run_id IS '审计事件关联阶段运行主键';
COMMENT ON COLUMN ai_audit_event.actor_type IS '发起HTTP尝试的主体类型';
COMMENT ON COLUMN ai_audit_event.actor_id IS '发起HTTP尝试的主体标识';
COMMENT ON COLUMN ai_audit_event.action IS '服务端观察到的操作名称';
COMMENT ON COLUMN ai_audit_event.target_type IS '操作目标类型';
COMMENT ON COLUMN ai_audit_event.target_id IS '操作目标标识';
COMMENT ON COLUMN ai_audit_event.attempt_status IS 'HTTP尝试结果状态';
COMMENT ON COLUMN ai_audit_event.previous_hash IS '同一审计链前一事件摘要';
COMMENT ON COLUMN ai_audit_event.event_hash IS '当前审计事件摘要';
COMMENT ON COLUMN ai_audit_event.payload_json IS '已脱敏审计载荷JSON';
COMMENT ON COLUMN ai_audit_event.created_at IS '审计事件发生时间';
