CREATE TABLE IF NOT EXISTS ai_client_device (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_code VARCHAR(80) NOT NULL,
  user_id VARCHAR(80) NOT NULL, public_key_digest VARCHAR(128), status VARCHAR(20) NOT NULL,
  last_seen_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 1, CONSTRAINT uk_ai_client_code UNIQUE(client_code)
);

CREATE TABLE IF NOT EXISTS ai_role_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role_id VARCHAR(100) NOT NULL,
  version VARCHAR(30) NOT NULL, display_name VARCHAR(200) NOT NULL,
  definition_logical_path VARCHAR(500) NOT NULL, digest VARCHAR(128) NOT NULL,
  permissions_json CLOB NOT NULL, status VARCHAR(20) NOT NULL,
  CONSTRAINT uk_ai_role_version UNIQUE(role_id, version)
);

CREATE TABLE IF NOT EXISTS ai_agent_registration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, agent_id VARCHAR(100) NOT NULL,
  version VARCHAR(30) NOT NULL, display_name VARCHAR(200) NOT NULL, endpoint_type VARCHAR(30) NOT NULL,
  endpoint VARCHAR(500) NOT NULL, protocol_version VARCHAR(30) NOT NULL, capabilities_json CLOB NOT NULL,
  config_digest VARCHAR(128) NOT NULL, status VARCHAR(20) NOT NULL,
  CONSTRAINT uk_ai_agent_registration UNIQUE(agent_id, version)
);

CREATE TABLE IF NOT EXISTS ai_role_agent_binding (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role_version_id BIGINT NOT NULL,
  agent_registration_id BIGINT NOT NULL, priority INT NOT NULL DEFAULT 1, status VARCHAR(20) NOT NULL,
  effective_from TIMESTAMP, effective_to TIMESTAMP,
  CONSTRAINT fk_ai_binding_role FOREIGN KEY(role_version_id) REFERENCES ai_role_version(id),
  CONSTRAINT fk_ai_binding_agent FOREIGN KEY(agent_registration_id) REFERENCES ai_agent_registration(id)
);

CREATE TABLE IF NOT EXISTS ai_task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_code VARCHAR(100) NOT NULL,
  root_thread_id VARCHAR(100) NOT NULL, title VARCHAR(500) NOT NULL, project VARCHAR(100) NOT NULL,
  status VARCHAR(40) NOT NULL, workflow_version VARCHAR(30) NOT NULL, state_version BIGINT NOT NULL,
  owner VARCHAR(100) NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_ai_task_code UNIQUE(task_code), CONSTRAINT uk_ai_root_thread UNIQUE(root_thread_id)
);

CREATE TABLE IF NOT EXISTS ai_task_stage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL,
  stage_code VARCHAR(120) NOT NULL, stage_type VARCHAR(50) NOT NULL, status VARCHAR(40) NOT NULL,
  role_version_id BIGINT NOT NULL, sequence_no INT NOT NULL, state_version BIGINT NOT NULL,
  CONSTRAINT uk_ai_task_stage_code UNIQUE(task_id, stage_code),
  CONSTRAINT uk_ai_task_stage_sequence UNIQUE(task_id, sequence_no),
  CONSTRAINT fk_ai_stage_task FOREIGN KEY(task_id) REFERENCES ai_task(id),
  CONSTRAINT fk_ai_stage_role FOREIGN KEY(role_version_id) REFERENCES ai_role_version(id)
);

CREATE TABLE IF NOT EXISTS ai_stage_run (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, stage_id BIGINT NOT NULL,
  run_code VARCHAR(100) NOT NULL, stage_thread_id VARCHAR(100) NOT NULL, agent_id VARCHAR(100),
  client_id VARCHAR(100) NOT NULL, attempt INT NOT NULL, status VARCHAR(40) NOT NULL,
  lease_token_digest VARCHAR(128) NOT NULL, lease_expires_at TIMESTAMP NOT NULL,
  last_sequence BIGINT NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_ai_run_code UNIQUE(run_code), CONSTRAINT uk_ai_stage_thread UNIQUE(stage_thread_id),
  CONSTRAINT fk_ai_run_stage FOREIGN KEY(stage_id) REFERENCES ai_task_stage(id)
);

CREATE TABLE IF NOT EXISTS ai_requirement_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL,
  item_code VARCHAR(100) NOT NULL, artifact_version INT NOT NULL, type VARCHAR(40) NOT NULL,
  source_ref VARCHAR(500), description CLOB NOT NULL, reason CLOB, priority VARCHAR(20),
  status VARCHAR(30) NOT NULL, acceptance CLOB NOT NULL, verification CLOB NOT NULL, digest VARCHAR(128) NOT NULL,
  CONSTRAINT uk_ai_requirement_item UNIQUE(task_id,item_code,artifact_version),
  CONSTRAINT fk_ai_requirement_task FOREIGN KEY(task_id) REFERENCES ai_task(id)
);

CREATE TABLE IF NOT EXISTS ai_artifact (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL, run_id BIGINT,
  artifact_code VARCHAR(100) NOT NULL, type VARCHAR(50) NOT NULL, standard_name VARCHAR(300) NOT NULL,
  logical_path VARCHAR(1000) NOT NULL, version INT NOT NULL, digest VARCHAR(128) NOT NULL,
  size_bytes BIGINT NOT NULL, gate_status VARCHAR(30) NOT NULL, created_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_ai_artifact_code UNIQUE(artifact_code),
  CONSTRAINT uk_ai_artifact_version UNIQUE(task_id,standard_name,version),
  CONSTRAINT fk_ai_artifact_task FOREIGN KEY(task_id) REFERENCES ai_task(id),
  CONSTRAINT fk_ai_artifact_run FOREIGN KEY(run_id) REFERENCES ai_stage_run(id)
);

CREATE TABLE IF NOT EXISTS ai_trace_link (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL,
  source_type VARCHAR(40) NOT NULL, source_id VARCHAR(100) NOT NULL, source_version INT NOT NULL,
  target_type VARCHAR(40) NOT NULL, target_id VARCHAR(100) NOT NULL, target_version INT NOT NULL,
  relation VARCHAR(40) NOT NULL,
  CONSTRAINT uk_ai_trace_link UNIQUE(task_id,source_type,source_id,source_version,target_type,target_id,target_version,relation)
);

CREATE TABLE IF NOT EXISTS ai_governance_package (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, candidate_id VARCHAR(100) NOT NULL,
  type VARCHAR(40) NOT NULL, scope VARCHAR(100) NOT NULL, candidate_digest VARCHAR(128) NOT NULL,
  manifest_json CLOB NOT NULL, status VARCHAR(30) NOT NULL, published_version VARCHAR(30),
  published_digest VARCHAR(128), supersedes_id BIGINT, approval_id BIGINT,
  CONSTRAINT uk_ai_governance_candidate UNIQUE(candidate_id)
);

CREATE TABLE IF NOT EXISTS ai_gate_definition_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, gate_id VARCHAR(100) NOT NULL,
  version VARCHAR(30) NOT NULL, package_id BIGINT, runner_type VARCHAR(50) NOT NULL,
  runner_digest VARCHAR(128) NOT NULL, input_schema_digest VARCHAR(128) NOT NULL,
  evidence_schema_digest VARCHAR(128) NOT NULL, status VARCHAR(30) NOT NULL,
  CONSTRAINT uk_ai_gate_definition UNIQUE(gate_id,version)
);

CREATE TABLE IF NOT EXISTS ai_gate_result (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, result_code VARCHAR(100) NOT NULL,
  task_id BIGINT NOT NULL, stage_id BIGINT, artifact_id BIGINT, artifact_version INT,
  gate_definition_id BIGINT, gate_id VARCHAR(100) NOT NULL, definition_version VARCHAR(30) NOT NULL,
  runner_digest VARCHAR(128) NOT NULL, artifact_digest VARCHAR(128) NOT NULL, result VARCHAR(20) NOT NULL,
  violations_json CLOB, evidence_digest VARCHAR(128) NOT NULL, status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NOT NULL, CONSTRAINT uk_ai_gate_result_code UNIQUE(result_code),
  CONSTRAINT fk_ai_gate_task FOREIGN KEY(task_id) REFERENCES ai_task(id)
);

CREATE TABLE IF NOT EXISTS ai_approval (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT, type VARCHAR(40) NOT NULL,
  target_type VARCHAR(40) NOT NULL, target_id VARCHAR(100) NOT NULL, target_version VARCHAR(30) NOT NULL,
  target_digest VARCHAR(128) NOT NULL, requester VARCHAR(100) NOT NULL, approver VARCHAR(100),
  decision VARCHAR(30), status VARCHAR(30) NOT NULL, version BIGINT NOT NULL, expires_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_progress_event (
  sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL, run_id BIGINT,
  event_type VARCHAR(80) NOT NULL, percent INT NOT NULL, message VARCHAR(1000),
  payload_digest VARCHAR(128) NOT NULL, payload_json CLOB, created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_ai_progress_task FOREIGN KEY(task_id) REFERENCES ai_task(id),
  CONSTRAINT fk_ai_progress_run FOREIGN KEY(run_id) REFERENCES ai_stage_run(id)
);
CREATE INDEX IF NOT EXISTS idx_ai_progress_task_sequence ON ai_progress_event(task_id,sequence);

CREATE TABLE IF NOT EXISTS ai_error_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, error_code VARCHAR(100) NOT NULL,
  task_id BIGINT, run_id BIGINT, role_id VARCHAR(100), type VARCHAR(40) NOT NULL, exit_code INT,
  message_masked CLOB, stack_digest VARCHAR(128), fingerprint VARCHAR(128), evidence_ref VARCHAR(500),
  created_at TIMESTAMP NOT NULL, CONSTRAINT uk_ai_error_code UNIQUE(error_code)
);

CREATE TABLE IF NOT EXISTS ai_retrospective (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL,
  failure_domain VARCHAR(20) NOT NULL, root_cause CLOB NOT NULL, code_fix_basis CLOB,
  improvement_target CLOB, rule_sentence CLOB, evidence_refs_json CLOB NOT NULL, status VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS ai_improvement_proposal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL, type VARCHAR(40) NOT NULL,
  candidate_id VARCHAR(100) NOT NULL, retrospective_id BIGINT NOT NULL, impact_digest VARCHAR(128) NOT NULL,
  validation_digest VARCHAR(128) NOT NULL, status VARCHAR(30) NOT NULL, approval_id BIGINT,
  CONSTRAINT uk_ai_improvement_candidate UNIQUE(candidate_id)
);

CREATE TABLE IF NOT EXISTS ai_audit_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_code VARCHAR(100) NOT NULL,
  task_id BIGINT, run_id BIGINT, actor_type VARCHAR(40) NOT NULL, actor_id VARCHAR(100) NOT NULL,
  action VARCHAR(100) NOT NULL, target_type VARCHAR(40), target_id VARCHAR(100), attempt_status VARCHAR(30) NOT NULL,
  previous_hash VARCHAR(128) NOT NULL, event_hash VARCHAR(128) NOT NULL, payload_json CLOB, created_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_ai_audit_event_code UNIQUE(event_code)
);
CREATE INDEX IF NOT EXISTS idx_ai_audit_task_time ON ai_audit_event(task_id,created_at);

CREATE TABLE IF NOT EXISTS ai_idempotency_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_id VARCHAR(100) NOT NULL,
  idempotency_key VARCHAR(150) NOT NULL, request_digest VARCHAR(128) NOT NULL, response_status INT,
  response_json CLOB, state VARCHAR(30) NOT NULL, expires_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_ai_idempotency UNIQUE(client_id,idempotency_key)
);

CREATE TABLE IF NOT EXISTS ai_task_agent_binding (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL, stage_id BIGINT NOT NULL,
  run_id BIGINT NOT NULL, role_version_id BIGINT NOT NULL, agent_registration_id BIGINT NOT NULL,
  registration_digest VARCHAR(128) NOT NULL, created_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_ai_task_agent_run UNIQUE(run_id)
);

CREATE TABLE IF NOT EXISTS ai_agent_state_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL, run_id BIGINT NOT NULL,
  agent_id VARCHAR(100) NOT NULL, sequence BIGINT NOT NULL, state VARCHAR(30) NOT NULL,
  facts_digest VARCHAR(128) NOT NULL, created_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_ai_agent_state_sequence UNIQUE(run_id,sequence)
);

