CREATE TABLE IF NOT EXISTS ai_client_device (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_code VARCHAR(80) NOT NULL,
  user_id VARCHAR(80) NOT NULL, public_key_digest VARCHAR(128), status VARCHAR(20) NOT NULL,
  last_seen_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 1, CONSTRAINT uk_ai_client_code UNIQUE(client_code)
);

COMMENT ON TABLE ai_client_device IS '本地Python客户端设备身份与在线状态表';
COMMENT ON COLUMN ai_client_device.id IS '客户端设备记录主键';
COMMENT ON COLUMN ai_client_device.client_code IS '客户端设备唯一编码';
COMMENT ON COLUMN ai_client_device.user_id IS '客户端所属稳定用户标识';
COMMENT ON COLUMN ai_client_device.public_key_digest IS '客户端公钥摘要';
COMMENT ON COLUMN ai_client_device.status IS '客户端设备状态';
COMMENT ON COLUMN ai_client_device.last_seen_at IS '客户端最后在线时间';
COMMENT ON COLUMN ai_client_device.version IS '客户端设备状态乐观锁版本';

CREATE TABLE IF NOT EXISTS ai_role_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role_id VARCHAR(100) NOT NULL,
  version VARCHAR(30) NOT NULL, display_name VARCHAR(200) NOT NULL,
  definition_logical_path VARCHAR(500) NOT NULL, digest VARCHAR(128) NOT NULL,
  permissions_json CLOB NOT NULL, status VARCHAR(20) NOT NULL,
  CONSTRAINT uk_ai_role_version UNIQUE(role_id, version)
);

COMMENT ON TABLE ai_role_version IS 'AI工厂角色定义的版本化登记表';
COMMENT ON COLUMN ai_role_version.id IS '角色版本记录主键';
COMMENT ON COLUMN ai_role_version.role_id IS '角色稳定标识';
COMMENT ON COLUMN ai_role_version.version IS '角色定义版本';
COMMENT ON COLUMN ai_role_version.display_name IS '角色显示名称';
COMMENT ON COLUMN ai_role_version.definition_logical_path IS '本地memory中角色定义文件逻辑路径';
COMMENT ON COLUMN ai_role_version.digest IS '角色定义内容摘要';
COMMENT ON COLUMN ai_role_version.permissions_json IS '角色权限清单JSON';
COMMENT ON COLUMN ai_role_version.status IS '角色版本状态';

CREATE TABLE IF NOT EXISTS ai_role_agent_binding (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role_version_id BIGINT NOT NULL,
  agent_registration_id BIGINT NOT NULL, priority INT NOT NULL DEFAULT 1, status VARCHAR(20) NOT NULL,
  effective_from TIMESTAMP, effective_to TIMESTAMP,
  CONSTRAINT fk_ai_binding_role FOREIGN KEY(role_version_id) REFERENCES ai_role_version(id),
  CONSTRAINT fk_ai_binding_agent FOREIGN KEY(agent_registration_id) REFERENCES ai_agent_registration(id)
);

COMMENT ON TABLE ai_role_agent_binding IS '角色版本与可启动Agent的优先级绑定表';
COMMENT ON COLUMN ai_role_agent_binding.id IS '角色Agent绑定记录主键';
COMMENT ON COLUMN ai_role_agent_binding.role_version_id IS '绑定的角色版本主键';
COMMENT ON COLUMN ai_role_agent_binding.agent_registration_id IS '绑定的Agent登记主键';
COMMENT ON COLUMN ai_role_agent_binding.priority IS '同一角色选择Agent时的优先级';
COMMENT ON COLUMN ai_role_agent_binding.status IS '角色Agent绑定状态';
COMMENT ON COLUMN ai_role_agent_binding.effective_from IS '绑定生效时间';
COMMENT ON COLUMN ai_role_agent_binding.effective_to IS '绑定失效时间';

CREATE TABLE IF NOT EXISTS ai_task_stage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL,
  stage_code VARCHAR(120) NOT NULL, stage_type VARCHAR(50) NOT NULL, status VARCHAR(40) NOT NULL,
  role_version_id BIGINT NOT NULL, sequence_no INT NOT NULL, state_version BIGINT NOT NULL,
  CONSTRAINT uk_ai_task_stage_code UNIQUE(task_id, stage_code),
  CONSTRAINT uk_ai_task_stage_sequence UNIQUE(task_id, sequence_no),
  CONSTRAINT fk_ai_stage_task FOREIGN KEY(task_id) REFERENCES ai_task(id),
  CONSTRAINT fk_ai_stage_role FOREIGN KEY(role_version_id) REFERENCES ai_role_version(id)
);

COMMENT ON TABLE ai_task_stage IS '任务工作流中的阶段编排与角色分配表';
COMMENT ON COLUMN ai_task_stage.id IS '任务阶段记录主键';
COMMENT ON COLUMN ai_task_stage.task_id IS '阶段所属任务主键';
COMMENT ON COLUMN ai_task_stage.stage_code IS '任务内唯一阶段编码';
COMMENT ON COLUMN ai_task_stage.stage_type IS '阶段业务类型';
COMMENT ON COLUMN ai_task_stage.status IS '任务阶段状态';
COMMENT ON COLUMN ai_task_stage.role_version_id IS '阶段采用的角色版本主键';
COMMENT ON COLUMN ai_task_stage.sequence_no IS '阶段在任务工作流中的执行顺序';
COMMENT ON COLUMN ai_task_stage.state_version IS '阶段状态乐观锁版本';

CREATE TABLE IF NOT EXISTS ai_requirement_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL,
  item_code VARCHAR(100) NOT NULL, artifact_version INT NOT NULL, type VARCHAR(40) NOT NULL,
  source_ref VARCHAR(500), description CLOB NOT NULL, reason CLOB, priority VARCHAR(20),
  status VARCHAR(30) NOT NULL, acceptance CLOB NOT NULL, verification CLOB NOT NULL, digest VARCHAR(128) NOT NULL,
  CONSTRAINT uk_ai_requirement_item UNIQUE(task_id,item_code,artifact_version),
  CONSTRAINT fk_ai_requirement_task FOREIGN KEY(task_id) REFERENCES ai_task(id)
);

COMMENT ON TABLE ai_requirement_item IS '任务需求文档拆分后的可开发功能要件表';
COMMENT ON COLUMN ai_requirement_item.id IS '需求要件记录主键';
COMMENT ON COLUMN ai_requirement_item.task_id IS '需求要件所属任务主键';
COMMENT ON COLUMN ai_requirement_item.item_code IS '任务内需求要件编码';
COMMENT ON COLUMN ai_requirement_item.artifact_version IS '需求要件来源产物版本';
COMMENT ON COLUMN ai_requirement_item.type IS '需求要件类型';
COMMENT ON COLUMN ai_requirement_item.source_ref IS '需求文档中的来源坐标';
COMMENT ON COLUMN ai_requirement_item.description IS '可独立开发功能的需求描述';
COMMENT ON COLUMN ai_requirement_item.reason IS '提出该需求要件的业务原因';
COMMENT ON COLUMN ai_requirement_item.priority IS '需求要件优先级';
COMMENT ON COLUMN ai_requirement_item.status IS '需求要件状态';
COMMENT ON COLUMN ai_requirement_item.acceptance IS '需求要件验收条件';
COMMENT ON COLUMN ai_requirement_item.verification IS '需求要件验证方法';
COMMENT ON COLUMN ai_requirement_item.digest IS '需求要件内容摘要';

CREATE TABLE IF NOT EXISTS ai_trace_link (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL,
  source_type VARCHAR(40) NOT NULL, source_id VARCHAR(100) NOT NULL, source_version INT NOT NULL,
  target_type VARCHAR(40) NOT NULL, target_id VARCHAR(100) NOT NULL, target_version INT NOT NULL,
  relation VARCHAR(40) NOT NULL,
  CONSTRAINT uk_ai_trace_link UNIQUE(task_id,source_type,source_id,source_version,target_type,target_id,target_version,relation)
);

COMMENT ON TABLE ai_trace_link IS '需求、设计、代码和测试产物之间的追踪关系表';
COMMENT ON COLUMN ai_trace_link.id IS '追踪关系记录主键';
COMMENT ON COLUMN ai_trace_link.task_id IS '追踪关系所属任务主键';
COMMENT ON COLUMN ai_trace_link.source_type IS '追踪源对象类型';
COMMENT ON COLUMN ai_trace_link.source_id IS '追踪源对象标识';
COMMENT ON COLUMN ai_trace_link.source_version IS '追踪源对象版本';
COMMENT ON COLUMN ai_trace_link.target_type IS '追踪目标对象类型';
COMMENT ON COLUMN ai_trace_link.target_id IS '追踪目标对象标识';
COMMENT ON COLUMN ai_trace_link.target_version IS '追踪目标对象版本';
COMMENT ON COLUMN ai_trace_link.relation IS '源对象与目标对象的关系类型';

CREATE TABLE IF NOT EXISTS ai_governance_package (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, candidate_id VARCHAR(100) NOT NULL,
  type VARCHAR(40) NOT NULL, scope VARCHAR(100) NOT NULL, candidate_digest VARCHAR(128) NOT NULL,
  manifest_json CLOB NOT NULL, status VARCHAR(30) NOT NULL, published_version VARCHAR(30),
  published_digest VARCHAR(128), supersedes_id BIGINT, approval_id BIGINT,
  CONSTRAINT uk_ai_governance_candidate UNIQUE(candidate_id)
);

COMMENT ON TABLE ai_governance_package IS '规则与门禁候选包的发布治理记录表';
COMMENT ON COLUMN ai_governance_package.id IS '治理候选包记录主键';
COMMENT ON COLUMN ai_governance_package.candidate_id IS '治理候选包唯一标识';
COMMENT ON COLUMN ai_governance_package.type IS '治理候选包类型';
COMMENT ON COLUMN ai_governance_package.scope IS '候选包适用范围';
COMMENT ON COLUMN ai_governance_package.candidate_digest IS '候选包内容摘要';
COMMENT ON COLUMN ai_governance_package.manifest_json IS '候选包清单JSON';
COMMENT ON COLUMN ai_governance_package.status IS '治理候选包状态';
COMMENT ON COLUMN ai_governance_package.published_version IS '审批通过后的发布版本';
COMMENT ON COLUMN ai_governance_package.published_digest IS '审批通过后的发布内容摘要';
COMMENT ON COLUMN ai_governance_package.supersedes_id IS '被当前候选包替代的历史包主键';
COMMENT ON COLUMN ai_governance_package.approval_id IS '候选包发布审批记录主键';

CREATE TABLE IF NOT EXISTS ai_gate_definition_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, gate_id VARCHAR(100) NOT NULL,
  version VARCHAR(30) NOT NULL, package_id BIGINT, runner_type VARCHAR(50) NOT NULL,
  runner_digest VARCHAR(128) NOT NULL, input_schema_digest VARCHAR(128) NOT NULL,
  evidence_schema_digest VARCHAR(128) NOT NULL, status VARCHAR(30) NOT NULL,
  CONSTRAINT uk_ai_gate_definition UNIQUE(gate_id,version)
);

COMMENT ON TABLE ai_gate_definition_version IS '可执行门禁定义的版本化登记表';
COMMENT ON COLUMN ai_gate_definition_version.id IS '门禁定义版本记录主键';
COMMENT ON COLUMN ai_gate_definition_version.gate_id IS '门禁稳定标识';
COMMENT ON COLUMN ai_gate_definition_version.version IS '门禁定义版本';
COMMENT ON COLUMN ai_gate_definition_version.package_id IS '门禁定义所属治理包主键';
COMMENT ON COLUMN ai_gate_definition_version.runner_type IS '门禁执行程序类型';
COMMENT ON COLUMN ai_gate_definition_version.runner_digest IS '门禁执行程序内容摘要';
COMMENT ON COLUMN ai_gate_definition_version.input_schema_digest IS '门禁输入结构摘要';
COMMENT ON COLUMN ai_gate_definition_version.evidence_schema_digest IS '门禁证据结构摘要';
COMMENT ON COLUMN ai_gate_definition_version.status IS '门禁定义版本状态';

CREATE TABLE IF NOT EXISTS ai_approval (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT, type VARCHAR(40) NOT NULL,
  target_type VARCHAR(40) NOT NULL, target_id VARCHAR(100) NOT NULL, target_version VARCHAR(30) NOT NULL,
  target_digest VARCHAR(128) NOT NULL, requester VARCHAR(100) NOT NULL, approver VARCHAR(100),
  decision VARCHAR(30), status VARCHAR(30) NOT NULL, version BIGINT NOT NULL, expires_at TIMESTAMP
);

COMMENT ON TABLE ai_approval IS '规则、门禁和任务变更的审批记录表';
COMMENT ON COLUMN ai_approval.id IS '审批记录主键';
COMMENT ON COLUMN ai_approval.task_id IS '审批关联任务主键';
COMMENT ON COLUMN ai_approval.type IS '审批业务类型';
COMMENT ON COLUMN ai_approval.target_type IS '审批目标对象类型';
COMMENT ON COLUMN ai_approval.target_id IS '审批目标对象标识';
COMMENT ON COLUMN ai_approval.target_version IS '审批目标对象版本';
COMMENT ON COLUMN ai_approval.target_digest IS '审批目标内容摘要';
COMMENT ON COLUMN ai_approval.requester IS '审批申请人标识';
COMMENT ON COLUMN ai_approval.approver IS '实际审批人标识';
COMMENT ON COLUMN ai_approval.decision IS '审批决定';
COMMENT ON COLUMN ai_approval.status IS '审批流程状态';
COMMENT ON COLUMN ai_approval.version IS '审批记录乐观锁版本';
COMMENT ON COLUMN ai_approval.expires_at IS '审批请求失效时间';

CREATE TABLE IF NOT EXISTS ai_error_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, error_code VARCHAR(100) NOT NULL,
  task_id BIGINT, run_id BIGINT, role_id VARCHAR(100), type VARCHAR(40) NOT NULL, exit_code INT,
  message_masked CLOB, stack_digest VARCHAR(128), fingerprint VARCHAR(128), evidence_ref VARCHAR(500),
  created_at TIMESTAMP NOT NULL, CONSTRAINT uk_ai_error_code UNIQUE(error_code)
);

COMMENT ON TABLE ai_error_log IS '任务与Agent运行错误的脱敏索引记录表';
COMMENT ON COLUMN ai_error_log.id IS '错误日志索引记录主键';
COMMENT ON COLUMN ai_error_log.error_code IS '错误事件唯一业务编码';
COMMENT ON COLUMN ai_error_log.task_id IS '错误关联任务主键';
COMMENT ON COLUMN ai_error_log.run_id IS '错误关联阶段运行主键';
COMMENT ON COLUMN ai_error_log.role_id IS '发生错误时执行的角色标识';
COMMENT ON COLUMN ai_error_log.type IS '错误类型';
COMMENT ON COLUMN ai_error_log.exit_code IS '本地进程退出码';
COMMENT ON COLUMN ai_error_log.message_masked IS '已脱敏错误消息';
COMMENT ON COLUMN ai_error_log.stack_digest IS '错误堆栈摘要';
COMMENT ON COLUMN ai_error_log.fingerprint IS '同类错误聚合指纹';
COMMENT ON COLUMN ai_error_log.evidence_ref IS '本地审计证据相对路径';
COMMENT ON COLUMN ai_error_log.created_at IS '错误发生时间';

CREATE TABLE IF NOT EXISTS ai_retrospective (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL,
  failure_domain VARCHAR(20) NOT NULL, root_cause CLOB NOT NULL, code_fix_basis CLOB,
  improvement_target CLOB, rule_sentence CLOB, evidence_refs_json CLOB NOT NULL, status VARCHAR(30) NOT NULL
);

COMMENT ON TABLE ai_retrospective IS '任务失败根因与规则改进复盘表';
COMMENT ON COLUMN ai_retrospective.id IS '复盘记录主键';
COMMENT ON COLUMN ai_retrospective.task_id IS '复盘所属任务主键';
COMMENT ON COLUMN ai_retrospective.failure_domain IS '失败所属领域';
COMMENT ON COLUMN ai_retrospective.root_cause IS '失败根因分析';
COMMENT ON COLUMN ai_retrospective.code_fix_basis IS '代码修复依据';
COMMENT ON COLUMN ai_retrospective.improvement_target IS '后续改进目标';
COMMENT ON COLUMN ai_retrospective.rule_sentence IS '候选防复发规则语句';
COMMENT ON COLUMN ai_retrospective.evidence_refs_json IS '复盘证据引用清单JSON';
COMMENT ON COLUMN ai_retrospective.status IS '复盘处理状态';

CREATE TABLE IF NOT EXISTS ai_improvement_proposal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL, type VARCHAR(40) NOT NULL,
  candidate_id VARCHAR(100) NOT NULL, retrospective_id BIGINT NOT NULL, impact_digest VARCHAR(128) NOT NULL,
  validation_digest VARCHAR(128) NOT NULL, status VARCHAR(30) NOT NULL, approval_id BIGINT,
  CONSTRAINT uk_ai_improvement_candidate UNIQUE(candidate_id)
);

COMMENT ON TABLE ai_improvement_proposal IS '复盘产生的规则或门禁改进提案表';
COMMENT ON COLUMN ai_improvement_proposal.id IS '改进提案记录主键';
COMMENT ON COLUMN ai_improvement_proposal.task_id IS '改进提案所属任务主键';
COMMENT ON COLUMN ai_improvement_proposal.type IS '改进提案类型';
COMMENT ON COLUMN ai_improvement_proposal.candidate_id IS '候选规则或门禁包标识';
COMMENT ON COLUMN ai_improvement_proposal.retrospective_id IS '提案来源复盘记录主键';
COMMENT ON COLUMN ai_improvement_proposal.impact_digest IS '改进影响分析摘要';
COMMENT ON COLUMN ai_improvement_proposal.validation_digest IS '改进验证结果摘要';
COMMENT ON COLUMN ai_improvement_proposal.status IS '改进提案状态';
COMMENT ON COLUMN ai_improvement_proposal.approval_id IS '改进提案审批记录主键';

CREATE TABLE IF NOT EXISTS ai_idempotency_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_id VARCHAR(100) NOT NULL,
  idempotency_key VARCHAR(150) NOT NULL, request_digest VARCHAR(128) NOT NULL, response_status INT,
  response_json CLOB, state VARCHAR(30) NOT NULL, expires_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_ai_idempotency UNIQUE(client_id,idempotency_key)
);

COMMENT ON TABLE ai_idempotency_record IS '本地Python调用HTTP接口的幂等请求记录表';
COMMENT ON COLUMN ai_idempotency_record.id IS '幂等请求记录主键';
COMMENT ON COLUMN ai_idempotency_record.client_id IS '发起请求的本地Python客户端标识';
COMMENT ON COLUMN ai_idempotency_record.idempotency_key IS '客户端提供的幂等键';
COMMENT ON COLUMN ai_idempotency_record.request_digest IS 'HTTP请求内容摘要';
COMMENT ON COLUMN ai_idempotency_record.response_status IS '首次请求的HTTP响应状态码';
COMMENT ON COLUMN ai_idempotency_record.response_json IS '首次请求的响应正文JSON';
COMMENT ON COLUMN ai_idempotency_record.state IS '幂等请求处理状态';
COMMENT ON COLUMN ai_idempotency_record.expires_at IS '幂等记录失效时间';

CREATE TABLE IF NOT EXISTS ai_task_agent_binding (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL, stage_id BIGINT NOT NULL,
  run_id BIGINT NOT NULL, role_version_id BIGINT NOT NULL, agent_registration_id BIGINT NOT NULL,
  registration_digest VARCHAR(128) NOT NULL, created_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_ai_task_agent_run UNIQUE(run_id)
);

COMMENT ON TABLE ai_task_agent_binding IS '任务阶段运行与实际Agent版本的审计绑定表';
COMMENT ON COLUMN ai_task_agent_binding.id IS '任务Agent绑定记录主键';
COMMENT ON COLUMN ai_task_agent_binding.task_id IS '绑定所属任务主键';
COMMENT ON COLUMN ai_task_agent_binding.stage_id IS '绑定所属任务阶段主键';
COMMENT ON COLUMN ai_task_agent_binding.run_id IS '绑定所属阶段运行主键';
COMMENT ON COLUMN ai_task_agent_binding.role_version_id IS '运行采用的角色版本主键';
COMMENT ON COLUMN ai_task_agent_binding.agent_registration_id IS '运行采用的Agent登记主键';
COMMENT ON COLUMN ai_task_agent_binding.registration_digest IS '启动时Agent登记快照摘要';
COMMENT ON COLUMN ai_task_agent_binding.created_at IS '任务Agent绑定创建时间';

CREATE TABLE IF NOT EXISTS ai_agent_state_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL, run_id BIGINT NOT NULL,
  agent_id VARCHAR(100) NOT NULL, sequence BIGINT NOT NULL, state VARCHAR(30) NOT NULL,
  facts_digest VARCHAR(128) NOT NULL, created_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_ai_agent_state_sequence UNIQUE(run_id,sequence)
);

COMMENT ON TABLE ai_agent_state_event IS '任务运行期间Agent状态变化的追加式审计事件表';
COMMENT ON COLUMN ai_agent_state_event.id IS 'Agent状态事件记录主键';
COMMENT ON COLUMN ai_agent_state_event.task_id IS 'Agent状态事件所属任务主键';
COMMENT ON COLUMN ai_agent_state_event.run_id IS 'Agent状态事件所属阶段运行主键';
COMMENT ON COLUMN ai_agent_state_event.agent_id IS '发生状态变化的Agent标识';
COMMENT ON COLUMN ai_agent_state_event.sequence IS '同一次运行内的状态事件序号';
COMMENT ON COLUMN ai_agent_state_event.state IS 'Agent运行状态';
COMMENT ON COLUMN ai_agent_state_event.facts_digest IS 'Agent状态事实摘要';
COMMENT ON COLUMN ai_agent_state_event.created_at IS 'Agent状态事件发生时间';
