-- ai_task 保存本地 Python 驱动任务的服务端控制面身份与状态。
CREATE TABLE IF NOT EXISTS ai_task (
  -- id 是服务端任务控制记录主键。
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_code VARCHAR(100) NOT NULL,
  root_thread_id VARCHAR(100) NOT NULL, title VARCHAR(500) NOT NULL, project VARCHAR(100) NOT NULL,
  status VARCHAR(40) NOT NULL, workflow_version VARCHAR(30) NOT NULL, state_version BIGINT NOT NULL,
  owner VARCHAR(100) NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_ai_task_code UNIQUE(task_code), CONSTRAINT uk_ai_root_thread UNIQUE(root_thread_id)
);

COMMENT ON TABLE ai_task IS '本地Python驱动任务的服务端控制面记录表';
COMMENT ON COLUMN ai_task.id IS '任务控制记录主键';
COMMENT ON COLUMN ai_task.task_code IS '任务唯一业务编码';
COMMENT ON COLUMN ai_task.root_thread_id IS '任务对应的Codex根会话标识';
COMMENT ON COLUMN ai_task.title IS '任务标题';
COMMENT ON COLUMN ai_task.project IS '任务所属项目编码';
COMMENT ON COLUMN ai_task.status IS '任务当前执行状态';
COMMENT ON COLUMN ai_task.workflow_version IS '任务采用的工作流版本';
COMMENT ON COLUMN ai_task.state_version IS '任务状态乐观锁版本';
COMMENT ON COLUMN ai_task.owner IS '任务责任主体标识';
COMMENT ON COLUMN ai_task.created_at IS '任务创建时间';
COMMENT ON COLUMN ai_task.updated_at IS '任务最后更新时间';
