-- ai_progress_event 保存 Python 游标监听和页面进度展示使用的追加式事件。
CREATE TABLE IF NOT EXISTS ai_progress_event (
  -- sequence 是任务进度事件的递增游标。
  sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL, run_id BIGINT,
  event_type VARCHAR(80) NOT NULL, percent INT NOT NULL, message VARCHAR(1000),
  payload_digest VARCHAR(128) NOT NULL, payload_json CLOB, created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_ai_progress_task FOREIGN KEY(task_id) REFERENCES ai_task(id),
  CONSTRAINT fk_ai_progress_run FOREIGN KEY(run_id) REFERENCES ai_stage_run(id)
);
CREATE INDEX IF NOT EXISTS idx_ai_progress_task_sequence ON ai_progress_event(task_id,sequence);

COMMENT ON TABLE ai_progress_event IS 'Python监听与页面展示使用的追加式任务进度事件表';
COMMENT ON COLUMN ai_progress_event.sequence IS '任务进度事件递增游标';
COMMENT ON COLUMN ai_progress_event.task_id IS '进度事件所属任务主键';
COMMENT ON COLUMN ai_progress_event.run_id IS '进度事件所属阶段运行主键';
COMMENT ON COLUMN ai_progress_event.event_type IS '进度事件类型';
COMMENT ON COLUMN ai_progress_event.percent IS '任务或阶段完成百分比';
COMMENT ON COLUMN ai_progress_event.message IS '进度事件显示消息';
COMMENT ON COLUMN ai_progress_event.payload_digest IS '进度事件载荷摘要';
COMMENT ON COLUMN ai_progress_event.payload_json IS '进度事件扩展载荷JSON';
COMMENT ON COLUMN ai_progress_event.created_at IS '进度事件发生时间';
