-- CommonSequenceSegment 保存 AI 工厂各业务表独立缓存主键号段。
CREATE TABLE IF NOT EXISTS CommonSequenceSegment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenantId BIGINT NOT NULL DEFAULT 1,
    lastOperateUserId BIGINT NOT NULL DEFAULT 1,
    seqCode VARCHAR(100) NOT NULL,
    seqName VARCHAR(200) NOT NULL,
    nextStartId BIGINT NOT NULL,
    stepSize INT NOT NULL,
    versionNo BIGINT NOT NULL,
    remark VARCHAR(500),
    sortnum INT NOT NULL DEFAULT 0,
    status INT NOT NULL DEFAULT 1,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_factory_sequence_code UNIQUE (seqCode),
    CONSTRAINT ck_ai_factory_sequence_next_start CHECK (nextStartId > 0),
    CONSTRAINT ck_ai_factory_sequence_step CHECK (stepSize > 0),
    CONSTRAINT ck_ai_factory_sequence_version CHECK (versionNo >= 0),
    CONSTRAINT ck_ai_factory_sequence_status CHECK (status IN (0, 1))
);

COMMENT ON TABLE CommonSequenceSegment IS 'AI工厂各业务表独立主键号段配置表';
COMMENT ON COLUMN CommonSequenceSegment.id IS '号段配置记录标识，由数据库自增避免循环发号';
COMMENT ON COLUMN CommonSequenceSegment.tenantId IS '号段配置所属租户标识';
COMMENT ON COLUMN CommonSequenceSegment.lastOperateUserId IS '最近维护号段配置的用户标识';
COMMENT ON COLUMN CommonSequenceSegment.seqCode IS '实际业务表名加主键字段形成的唯一号段编码';
COMMENT ON COLUMN CommonSequenceSegment.seqName IS '号段中文名称';
COMMENT ON COLUMN CommonSequenceSegment.nextStartId IS '下一次成功抢号的起始主键，只允许向前推进';
COMMENT ON COLUMN CommonSequenceSegment.stepSize IS '单个进程一次缓存的号段长度';
COMMENT ON COLUMN CommonSequenceSegment.versionNo IS '多进程抢号乐观锁版本';
COMMENT ON COLUMN CommonSequenceSegment.remark IS '号段主键策略说明';
COMMENT ON COLUMN CommonSequenceSegment.sortnum IS '号段配置业务排序值';
COMMENT ON COLUMN CommonSequenceSegment.status IS '逻辑状态：1启用、0停用';
COMMENT ON COLUMN CommonSequenceSegment.createdAt IS '配置创建时间';
COMMENT ON COLUMN CommonSequenceSegment.updatedAt IS '配置更新时间';
