server.port=8080

spring.application.name=selplat-uniauth-backend
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:selplat_uniauth;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-uniauth.sql
spring.sql.init.data-locations=classpath:data-uniauth.sql

mybatis.mapper-locations=classpath*:com/sp/selplat/uniauth/**/dao/mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
