-- ua_tenant 用于保存统一认证域下的租户主数据，当前本地最小运行主要给管理员账号提供 tenant_id 归属。
CREATE TABLE IF NOT EXISTS ua_tenant (
    -- 租户主键由数据库自增生成，供用户、组织等后续领域表稳定引用。
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- tenant_code 是租户业务编码，后续多租户接入时可作为外部识别码使用，因此保持唯一。
    tenant_code VARCHAR(50) NOT NULL UNIQUE,
    -- tenant_name 保存租户展示名称，供后台列表、详情和切租户场景直接显示。
    tenant_name VARCHAR(200) NOT NULL,
    -- tenant_status 表示租户是否处于可用状态，默认 enabled 便于本地种子数据启动即生效。
    tenant_status VARCHAR(30) NOT NULL DEFAULT 'enabled',
    -- contact_name 记录租户默认联系人姓名，便于后续运营或通知场景直接复用。
    contact_name VARCHAR(100),
    -- contact_email 记录租户联系人邮箱，后续可用于邮件通知或租户资料维护。
    contact_email VARCHAR(100),
    -- contact_phone 记录租户联系人电话，便于控制台展示和人工联系。
    contact_phone VARCHAR(50),
    -- expire_at 预留租户到期时间，后续可用于租户停用或续费判断。
    expire_at TIMESTAMP,
    -- created_at 记录租户创建时间，便于审计和初始化数据核对。
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- updated_at 记录租户最后更新时间，便于后续维护和变更追踪。
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ua_user 保存统一认证用户账号，当前本地联调主要依赖这里的管理员种子数据完成登录与用户查询验证。
CREATE TABLE IF NOT EXISTS ua_user (
    -- 用户主键由数据库自增生成，供认证、权限和后续业务域稳定关联。
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- tenant_id 表示用户所属租户，当前虽然未建外键，但与初始化的默认租户数据保持配套关系。
    tenant_id BIGINT,
    -- login_name 是登录账号，要求唯一，供认证入口直接按账号检索用户。
    login_name VARCHAR(100) NOT NULL UNIQUE,
    -- password_hash 保存加密后的口令摘要，避免明文密码落库。
    password_hash VARCHAR(255) NOT NULL,
    -- display_name 保存用户中文或默认展示名，供界面抬头、列表和详情显示。
    display_name VARCHAR(100) NOT NULL,
    -- display_name_kana 预留日文假名展示字段，兼容日语场景下的人名检索和显示。
    display_name_kana VARCHAR(100),
    -- locale 记录用户默认语言区域，默认 zh-CN 方便本地最小运行直接使用中文界面。
    locale VARCHAR(20) DEFAULT 'zh-CN',
    -- email 保存用户邮箱，供通知和账号资料展示使用。
    email VARCHAR(100),
    -- phone 保存用户联系电话，供资料页和后续通知场景使用。
    phone VARCHAR(50),
    -- user_status 表示账号是否有效，默认 ACTIVE 让初始化管理员可直接登录。
    user_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    -- locked_flag 表示账号是否被锁定，默认 0 代表未锁定，便于最小环境直接验证。
    locked_flag TINYINT DEFAULT 0,
    -- expired_at 预留账号到期时间，后续可用于临时账号或合同到期控制。
    expired_at TIMESTAMP,
    -- created_at 记录用户创建时间，便于审计和初始化检查。
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- updated_at 记录用户最后更新时间，便于后续资料修改和同步逻辑追踪。
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
