-- CommonSequenceSegment 用于保存当前工程按模块缓存主键号段的公共配置。
CREATE TABLE IF NOT EXISTS CommonSequenceSegment (
    -- id 作为号段配置记录标识，供后台维护和后续扩展稳定引用。
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- tenantId 表达当前号段配置归属的租户边界，便于多租户环境下隔离不同租户的主键规则。
    tenantId BIGINT NOT NULL,
    -- lastOperateUserId 记录最近维护该号段配置的用户标识，便于主表直接回看最新维护责任人。
    lastOperateUserId BIGINT NOT NULL,
    -- seqCode 保存模块号段编码，供发号服务按编码快速定位目标配置，要求全局唯一。
    seqCode VARCHAR(64) NOT NULL UNIQUE,
    -- seqName 保存号段中文名称，便于后台配置页面和运维排查时直接识别。
    seqName VARCHAR(128) NOT NULL,
    -- nextStartId 保存下一次成功抢号时可分配的起始主键值。
    nextStartId BIGINT NOT NULL,
    -- stepSize 保存每次成功抢号后分配给单个实例的号段长度。
    stepSize INT NOT NULL,
    -- versionNo 保存乐观锁版本号，供多实例并发抢号时做原子更新控制。
    versionNo INT NOT NULL DEFAULT 0,
    -- remark 保存号段补充说明，便于记录该模块主键策略或特殊约束。
    remark VARCHAR(255),
    -- sortnum 保存配置展示顺序，便于后台配置页按业务顺序稳定展示。
    sortnum DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    -- status 保存逻辑状态，默认 1 表示启用，0 或其他值表示停用或删除。
    status INTEGER NOT NULL DEFAULT 1,
    -- createdAt 保存号段配置创建时间，便于排查初始化来源。
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- updatedAt 保存号段配置最后更新时间，便于确认最近一次维护时间。
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE CommonSequenceSegment IS '公共主键号段配置表';
COMMENT ON COLUMN CommonSequenceSegment.id IS '号段配置记录标识';
COMMENT ON COLUMN CommonSequenceSegment.tenantId IS '数据所属租户标识';
COMMENT ON COLUMN CommonSequenceSegment.lastOperateUserId IS '最近操作用户标识';
COMMENT ON COLUMN CommonSequenceSegment.seqCode IS '号段编码';
COMMENT ON COLUMN CommonSequenceSegment.seqName IS '号段中文名称';
COMMENT ON COLUMN CommonSequenceSegment.nextStartId IS '下次分配起始主键';
COMMENT ON COLUMN CommonSequenceSegment.stepSize IS '单次号段长度';
COMMENT ON COLUMN CommonSequenceSegment.versionNo IS '乐观锁版本号';
COMMENT ON COLUMN CommonSequenceSegment.remark IS '号段补充说明';
COMMENT ON COLUMN CommonSequenceSegment.sortnum IS '业务排序值';
COMMENT ON COLUMN CommonSequenceSegment.status IS '逻辑状态标记';
COMMENT ON COLUMN CommonSequenceSegment.createdAt IS '数据创建时间';
COMMENT ON COLUMN CommonSequenceSegment.updatedAt IS '数据更新时间';

-- UniauthTenant 用于保存统一认证域下的租户主数据，当前本地最小运行主要给管理员账号提供 tenantId 归属。
CREATE TABLE IF NOT EXISTS UniauthTenant (
    -- id 作为租户记录标识，供用户、组织等后续领域表稳定引用。
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- tenantId 记录当前数据归属的租户标识，租户主表自身默认保存本租户主键。
    tenantId BIGINT NOT NULL,
    -- lastOperateUserId 记录最后操作该租户数据的用户标识，便于主表直接回看最近维护责任人。
    lastOperateUserId BIGINT NOT NULL,
    -- tenantCode 保存租户业务编码，便于外部系统识别和切换租户时稳定引用。
    tenantCode VARCHAR(50) NOT NULL UNIQUE,
    -- tenantName 保存租户展示名称，供后台列表、详情和切租户场景直接显示。
    tenantName VARCHAR(200) NOT NULL,
    -- tenantStatus 保存租户业务状态，便于区分启用、停用等租户生命周期状态。
    tenantStatus VARCHAR(30) NOT NULL DEFAULT 'enabled',
    -- contactName 保存默认联系人姓名，便于租户资料和通知场景直接复用。
    contactName VARCHAR(100),
    -- contactEmail 保存联系人邮箱，便于租户通知和资料维护场景使用。
    contactEmail VARCHAR(100),
    -- contactPhone 保存联系人电话，便于控制台展示和人工联系。
    contactPhone VARCHAR(50),
    -- expireAt 保存租户到期时间，供后续续费或停用判断使用。
    expireAt TIMESTAMP,
    -- sortnum 保存手工排序值，便于租户列表按业务顺序稳定展示。
    sortnum DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    -- status 保存逻辑状态，默认 1 表示有效，0 表示删除或停用记录。
    status INTEGER NOT NULL DEFAULT 1,
    -- createdAt 保存创建时间，便于审计初始化和后续新建来源。
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- updatedAt 保存最后更新时间，便于跟踪后续资料变更。
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE UniauthTenant IS '统一认证租户主表';
COMMENT ON COLUMN UniauthTenant.id IS '租户主记录标识';
COMMENT ON COLUMN UniauthTenant.tenantId IS '当前数据归属租户标识';
COMMENT ON COLUMN UniauthTenant.lastOperateUserId IS '最近操作用户标识';
COMMENT ON COLUMN UniauthTenant.tenantCode IS '租户业务编码';
COMMENT ON COLUMN UniauthTenant.tenantName IS '租户展示名称';
COMMENT ON COLUMN UniauthTenant.tenantStatus IS '租户业务状态';
COMMENT ON COLUMN UniauthTenant.contactName IS '默认联系人姓名';
COMMENT ON COLUMN UniauthTenant.contactEmail IS '默认联系人邮箱';
COMMENT ON COLUMN UniauthTenant.contactPhone IS '默认联系人电话';
COMMENT ON COLUMN UniauthTenant.expireAt IS '租户到期时间';
COMMENT ON COLUMN UniauthTenant.sortnum IS '业务排序值';
COMMENT ON COLUMN UniauthTenant.status IS '逻辑状态标记';
COMMENT ON COLUMN UniauthTenant.createdAt IS '数据创建时间';
COMMENT ON COLUMN UniauthTenant.updatedAt IS '数据更新时间';

-- ua_user 保存统一认证用户账号，当前本地联调主要依赖这里的管理员种子数据完成登录与用户查询验证。
CREATE TABLE IF NOT EXISTS UniauthUser (
    -- id 作为用户记录标识，供认证、权限和后续业务域稳定关联。
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- tenantId 表达用户所属租户标识，所有用户记录都必须落到明确租户边界下。
    tenantId BIGINT NOT NULL,
    -- lastOperateUserId 记录最后操作该用户数据的用户标识，便于主表直接回看最近维护责任人。
    lastOperateUserId BIGINT NOT NULL,
    -- loginName 与 UniauthUser#loginName 完全一致，要求唯一，供认证入口直接按账号检索用户。
    loginName VARCHAR(100) NOT NULL UNIQUE,
    -- passwordHash 与 UniauthUser#passwordHash 完全一致，保存加密后的口令摘要。
    passwordHash VARCHAR(255) NOT NULL,
    -- displayName 与 UniauthUser#displayName 完全一致，保存用户中文或默认展示名。
    displayName VARCHAR(100) NOT NULL,
    -- displayNameKana 与 UniauthUser#displayNameKana 完全一致，兼容日语场景下的人名检索和显示。
    displayNameKana VARCHAR(100),
    -- locale 记录用户默认语言区域，默认 zh-CN 方便本地最小运行直接使用中文界面。
    locale VARCHAR(20) DEFAULT 'zh-CN',
    -- email 保存用户邮箱，供通知和账号资料展示使用。
    email VARCHAR(100),
    -- phone 保存用户联系电话，供资料页和后续通知场景使用。
    phone VARCHAR(50),
    -- userStatus 与 UniauthUser#userStatus 完全一致，表示账号是否有效，默认 ACTIVE 让初始化管理员可直接登录。
    userStatus VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    -- lockedFlag 与 UniauthUser#lockedFlag 完全一致，表示账号是否被锁定，默认 0 代表未锁定。
    lockedFlag TINYINT DEFAULT 0,
    -- expiredAt 与 UniauthUser#expiredAt 完全一致，表达账号到期时间。
    expiredAt TIMESTAMP,
    -- sortnum 保存手工排序值，便于账号列表按业务顺序稳定展示。
    sortnum DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    -- status 与 Domain#status 一致，默认 1 表示有效，0 表示逻辑删除。
    status INTEGER NOT NULL DEFAULT 1,
    -- createdAt 与 Domain#createdAt 完全一致，记录用户创建时间。
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- updatedAt 与 Domain#updatedAt 完全一致，记录用户最后更新时间。
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE UniauthUser IS '统一认证用户主表';
COMMENT ON COLUMN UniauthUser.id IS '用户主记录标识';
COMMENT ON COLUMN UniauthUser.tenantId IS '用户所属租户标识';
COMMENT ON COLUMN UniauthUser.lastOperateUserId IS '最近操作用户标识';
COMMENT ON COLUMN UniauthUser.loginName IS '登录账号';
COMMENT ON COLUMN UniauthUser.passwordHash IS '口令摘要';
COMMENT ON COLUMN UniauthUser.displayName IS '默认展示姓名';
COMMENT ON COLUMN UniauthUser.displayNameKana IS '姓名假名';
COMMENT ON COLUMN UniauthUser.locale IS '默认语言区域';
COMMENT ON COLUMN UniauthUser.email IS '联系邮箱';
COMMENT ON COLUMN UniauthUser.phone IS '联系电话';
COMMENT ON COLUMN UniauthUser.userStatus IS '账号业务状态';
COMMENT ON COLUMN UniauthUser.lockedFlag IS '锁定标记';
COMMENT ON COLUMN UniauthUser.expiredAt IS '账号到期时间';
COMMENT ON COLUMN UniauthUser.sortnum IS '业务排序值';
COMMENT ON COLUMN UniauthUser.status IS '逻辑状态标记';
COMMENT ON COLUMN UniauthUser.createdAt IS '数据创建时间';
COMMENT ON COLUMN UniauthUser.updatedAt IS '数据更新时间';
