-- ua_tenant 用于保存统一认证域下的租户主数据，当前本地最小运行主要给管理员账号提供 tenant_id 归属。
CREATE TABLE IF NOT EXISTS ua_tenant (
    -- 租户主键由数据库自增生成，供用户、组织等后续领域表稳定引用。
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- tenant_code 是租户业务编码，后续多租户接入时可作为外部识别码使用，因此保持唯一。
    tenant_code VARCHAR(50) NOT NULL UNIQUE,
    -- tenant_name 保存租户展示名称，供后台列表、详情和切租户场景直接显示。
    tenant_name VARCHAR(200) NOT NULL,
    -- tenant_status 表示租户是否处于可用状态，默认 enabled 便于本地种子数据启动即生效。
    tenant_status VARCHAR(30) NOT NULL DEFAULT 'enabled',
    -- contact_name 记录租户默认联系人姓名，便于后续运营或通知场景直接复用。
    contact_name VARCHAR(100),
    -- contact_email 记录租户联系人邮箱，后续可用于邮件通知或租户资料维护。
    contact_email VARCHAR(100),
    -- contact_phone 记录租户联系人电话，便于控制台展示和人工联系。
    contact_phone VARCHAR(50),
    -- expire_at 预留租户到期时间，后续可用于租户停用或续费判断。
    expire_at TIMESTAMP,
    -- created_at 记录租户创建时间，便于审计和初始化数据核对。
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- updated_at 记录租户最后更新时间，便于后续维护和变更追踪。
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ua_user 保存统一认证用户账号，当前本地联调主要依赖这里的管理员种子数据完成登录与用户查询验证。
CREATE TABLE IF NOT EXISTS UniauthUser (
    -- 用户主键由数据库自增生成，供认证、权限和后续业务域稳定关联。
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- tenantId 与 UniauthUser#tenantId 完全一致，表达用户所属租户主键。
    tenantId BIGINT,
    -- loginName 与 UniauthUser#loginName 完全一致，要求唯一，供认证入口直接按账号检索用户。
    loginName VARCHAR(100) NOT NULL UNIQUE,
    -- passwordHash 与 UniauthUser#passwordHash 完全一致，保存加密后的口令摘要。
    passwordHash VARCHAR(255) NOT NULL,
    -- displayName 与 UniauthUser#displayName 完全一致，保存用户中文或默认展示名。
    displayName VARCHAR(100) NOT NULL,
    -- displayNameKana 与 UniauthUser#displayNameKana 完全一致，兼容日语场景下的人名检索和显示。
    displayNameKana VARCHAR(100),
    -- locale 记录用户默认语言区域，默认 zh-CN 方便本地最小运行直接使用中文界面。
    locale VARCHAR(20) DEFAULT 'zh-CN',
    -- email 保存用户邮箱，供通知和账号资料展示使用。
    email VARCHAR(100),
    -- phone 保存用户联系电话，供资料页和后续通知场景使用。
    phone VARCHAR(50),
    -- userStatus 与 UniauthUser#userStatus 完全一致，表示账号是否有效，默认 ACTIVE 让初始化管理员可直接登录。
    userStatus VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    -- lockedFlag 与 UniauthUser#lockedFlag 完全一致，表示账号是否被锁定，默认 0 代表未锁定。
    lockedFlag TINYINT DEFAULT 0,
    -- expiredAt 与 UniauthUser#expiredAt 完全一致，表达账号到期时间。
    expiredAt TIMESTAMP,
    -- createdAt 与 Domain#createdAt 完全一致，记录用户创建时间。
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- updatedAt 与 Domain#updatedAt 完全一致，记录用户最后更新时间。
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
