-- MdaControlSchemaMigrationTest.legacyUpgrade Case
CREATE TABLE CommonSequenceSegment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenantId BIGINT NOT NULL,
    lastOperateUserId BIGINT NOT NULL,
    seqCode VARCHAR(64) NOT NULL UNIQUE,
    seqName VARCHAR(128) NOT NULL,
    nextStartId BIGINT NOT NULL,
    stepSize INT NOT NULL,
    versionNo INT NOT NULL DEFAULT 0,
    remark VARCHAR(255),
    sortnum DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    status INTEGER NOT NULL DEFAULT 1,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MdaConnectionProfile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenantId BIGINT NOT NULL,
    lastOperateUserId BIGINT NOT NULL,
    connectionName VARCHAR(120) NOT NULL UNIQUE,
    databaseType VARCHAR(20) NOT NULL,
    host VARCHAR(255),
    port INTEGER,
    databaseName VARCHAR(240) NOT NULL,
    schemaName VARCHAR(120),
    username VARCHAR(120),
    password VARCHAR(1000) NOT NULL DEFAULT '',
    customJdbcUrl VARCHAR(1000),
    jdbcParameters VARCHAR(1000),
    defaultAutoCommit BOOLEAN NOT NULL DEFAULT TRUE,
    sortnum DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    status INTEGER NOT NULL DEFAULT 1,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO CommonSequenceSegment (
    tenantId,
    lastOperateUserId,
    seqCode,
    seqName,
    nextStartId,
    stepSize,
    versionNo,
    remark,
    sortnum,
    status)
VALUES (1, 1, 'UniauthUserId', '旧库误留统一认证用户号段', 100000, 1000, 0, '等待迁移', 10.00, 1);

INSERT INTO MdaConnectionProfile (
    id, tenantId, lastOperateUserId, connectionName, databaseType, databaseName, username, password, status)
VALUES (10003, 1, 1, '旧库连接', 'H2', 'mem:legacy_mda', 'sa', 'legacy-password', 1);
