CREATE TABLE IF NOT EXISTS ua_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    login_name VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    display_name_kana VARCHAR(100),
    locale VARCHAR(20) DEFAULT 'zh-CN',
    email VARCHAR(100),
    phone VARCHAR(50),
    user_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    locked_flag TINYINT DEFAULT 0,
    expired_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ua_user_tenant_id ON ua_user (tenant_id);
CREATE INDEX IF NOT EXISTS idx_ua_user_status ON ua_user (user_status);

COMMENT ON TABLE ua_user IS '权限系统用户主表，存放登录账号、展示名称、语言、联系方式和账号状态。';

COMMENT ON COLUMN ua_user.id IS '用户主键，由数据库自增生成。';
COMMENT ON COLUMN ua_user.tenant_id IS '所属租户主键，为空时表示平台级账号。';
COMMENT ON COLUMN ua_user.login_name IS '登录名，作为权限系统稳定登录标识，必须全局唯一。';
COMMENT ON COLUMN ua_user.password_hash IS '密码哈希，不保存明文密码。';
COMMENT ON COLUMN ua_user.display_name IS '显示名称，用于平台界面和业务界面展示。';
COMMENT ON COLUMN ua_user.display_name_kana IS '显示名称假名，供日语场景辅助展示。';
COMMENT ON COLUMN ua_user.locale IS '用户默认语言区域，例如 zh-CN、ja-JP。';
COMMENT ON COLUMN ua_user.email IS '联系邮箱。';
COMMENT ON COLUMN ua_user.phone IS '联系电话。';
COMMENT ON COLUMN ua_user.user_status IS '用户状态，例如 ACTIVE、DISABLED。';
COMMENT ON COLUMN ua_user.locked_flag IS '锁定标记，0 表示未锁定，1 表示已锁定。';
COMMENT ON COLUMN ua_user.expired_at IS '账号失效时间，到期后可配合状态控制禁止登录。';
COMMENT ON COLUMN ua_user.created_at IS '创建时间。';
COMMENT ON COLUMN ua_user.updated_at IS '最后更新时间。';
