CREATE TABLE IF NOT EXISTS ReferenceDataType (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projectCode VARCHAR(64) NOT NULL,
    resourceCode VARCHAR(64) NOT NULL,
    nameZh VARCHAR(120) NOT NULL,
    nameJa VARCHAR(120),
    nameEn VARCHAR(120),
    descriptionZh VARCHAR(500),
    descriptionJa VARCHAR(500),
    descriptionEn VARCHAR(500),
    dataShape VARCHAR(16) NOT NULL DEFAULT 'BOTH',
    status INTEGER NOT NULL DEFAULT 1,
    sortnum DECIMAL(18, 2) NOT NULL DEFAULT 0,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_reference_data_type_coordinate UNIQUE (projectCode, resourceCode),
    CONSTRAINT ck_reference_data_type_shape CHECK (dataShape IN ('TREE', 'OPTIONS', 'BOTH')),
    CONSTRAINT ck_reference_data_type_status CHECK (status IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS ReferenceDataItem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typeId BIGINT NOT NULL,
    parentId BIGINT,
    itemCode VARCHAR(100) NOT NULL,
    itemValue VARCHAR(200) NOT NULL,
    labelZh VARCHAR(200) NOT NULL,
    labelJa VARCHAR(200),
    labelEn VARCHAR(200),
    groupCode VARCHAR(100),
    attributesJson CLOB,
    disabled BOOLEAN NOT NULL DEFAULT FALSE,
    status INTEGER NOT NULL DEFAULT 1,
    sortnum DECIMAL(18, 2) NOT NULL DEFAULT 0,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reference_data_item_type FOREIGN KEY (typeId) REFERENCES ReferenceDataType(id),
    CONSTRAINT fk_reference_data_item_parent FOREIGN KEY (parentId) REFERENCES ReferenceDataItem(id),
    CONSTRAINT uk_reference_data_item_code UNIQUE (typeId, itemCode),
    CONSTRAINT ck_reference_data_item_status CHECK (status IN (0, 1, 2))
);

CREATE INDEX IF NOT EXISTS idx_reference_data_type_status_sort
    ON ReferenceDataType(status, sortnum, id);

CREATE INDEX IF NOT EXISTS idx_reference_data_item_type_status_sort
    ON ReferenceDataItem(typeId, status, sortnum, id);
