import type { LocaleValue } from "../value/base.value.js";

/** 固定界面资源的稳定键；用户输入、历史正文与技术异常不得使用这些键。 */
export type FixedUiTextKey =
  | `conversation${string}`
  | `collaboration${string}`
  | "language" | "languageSaving" | "languageSaveFailed" | "retry" | "dismiss"
  | "settingsReadRecovered" | "screenshotSettingsReadTitle" | "screenshotSettingsReadDetail"
  | "close" | "technicalDetails" | "loadingScreenshot" | "missingText"
  | "managedModeConversation" | "managedModeRequirement" | "managedModeTask" | "managedModeTest"
  | "managedStageConfirmIntent" | "managedStageExecutePlan" | "managedStageTest" | "managedStageRetest"
  | "managedStageReanalyze" | "managedStageRerun"
  | "streamProcess" | "streamActivityCount" | "streamChangedFiles"
  | "streamActivityReasoning" | "streamActivityCommandExecution" | "streamActivityCommandPolicy"
  | "streamActivityFileChange" | "streamActivityMcpToolCall" | "streamActivityDynamicToolCall"
  | "streamActivityCollabToolCall" | "streamActivityWebSearch" | "streamActivityImageView"
  | "streamActivityContextCompaction" | "streamActivityAgentMessage" | "streamUnknownActivity"
  | "streamStarting" | "streamInProgress" | "streamPlanning" | "streamReasoning"
  | "streamResponding" | "streamCommandExecution" | "streamFileChange"
  | "streamInterrupted" | "streamFailed" | "streamCompleted" | "streamConversationCompleted"
  | "streamRequirementCompleted" | "streamTaskCompleted" | "streamTestCompleted"
  | "screenshotSelect" | "screenshotSelectHint" | "screenshotAnnotate" | "screenshotDone"
  | "screenshotPen" | "screenshotRectangle" | "screenshotUndo" | "screenshotClear"
  | "screenshotClearConfirm" | "screenshotCancel" | "screenshotBack" | "screenshotSaving"
  | "screenshotLoadFailed" | "screenshotSaveFailed" | "screenshotWindowControl"
  | "screenshotCapturedScreen" | "screenshotResizeAnnotation"
  | "workspaceFilePreview" | "workspaceCloseFilePreview" | "workspaceCopyContent"
  | "workspaceContentCopied" | "workspaceCopyFailed"
  | "developerTitle" | "developerSettings" | "developerSettingsOpen" | "developerSettingsClose"
  | "workspaceList" | "workspaceAdd" | "workspacePrimary" | "workspaceMakePrimary" | "workspaceRemove" | "workspaceRemoveConfirm" | "workspaceMinimum"
  | "sandboxReadOnly" | "sandboxWrite" | "sandboxReadOnlyTip" | "sandboxWriteTip" | "account" | "signedOut" | "signOut" | "signIn" | "browserOpened"
  | "tempFiles" | "openTemp" | "clearTemp" | "clearTempConfirm" | "trustedCommands" | "trustedCommandsHint" | "clearTrustedCommands" | "clearTrustedConfirm"
  | "auditLogs" | "openAuditLogs" | "noAuditTask" | "attachment" | "automaticTestTriggered" | "screenSourceUnavailable"
  | "memoryDatabaseDisabledTitle" | "memoryDatabaseDisabledDetail" | "sidebarResize"
  | "testDataTitle" | "testDataSummary" | "testDataDetail" | "testDataAction" | "testDataBusy" | "testDataConfirm" | "testDataRestart" | "testDataRestartConfirm" | "testDataResult" | "testDataCandidates" | "testDataClearFailed" | "testDataRestartFailed"
  | "resetCategoryCollaboration" | "resetCategoryEvolution" | "resetCategoryLinghu" | "resetCategoryWorkflow"
  | "modelDefault" | "modelDefaultLabel" | "modelRuntimeDownloaded" | "modelRuntimeBundled" | "modelCatalogLoading" | "modelCatalogLoaded" | "modelCatalogAstraPresent" | "modelCatalogAstraMissing" | "modelSettingsTitle" | "modelSettingsSummary" | "modelLoading" | "modelEffort" | "modelEffortDefault" | "modelSpeed" | "modelStandardSpeed" | "modelFastSpeed" | "modelUnavailable" | "modelSpeedUnavailable" | "modelCatalogFailed" | "settingsSaveFailed"
  | "corpusTitle" | "corpusEnabled" | "corpusDisabled" | "corpusDetail" | "corpusIngestionPrefix" | "corpusStart" | "corpusStop" | "corpusBackfill" | "corpusBackfillBusy" | "corpusBackfillAria" | "corpusStopped"
  | "auditReasonCount" | "auditRunning" | "auditCompleted" | "auditPartial" | "auditFailed" | "auditInterrupted"
  | "reasoningNone" | "reasoningMinimal" | "reasoningLow" | "reasoningMedium" | "reasoningHigh" | "reasoningXhigh" | "reasoningMax" | "reasoningUltra"
  | "settingsPanelResize" | "settingsPanelResizeRight" | "settingsPanelResizeReset" | "languageOptionZhCn" | "languageOptionJa" | "languageOptionEn" | "sandbox" | "recordUnit"
  | "sidebarExpand" | "sidebarCollapse" | "taskExpand" | "taskCollapse" | "taskSection" | "taskSectionHeading"
  | "operatingMode" | "operatingSingleConversation" | "operatingCollaboration" | "collaborationTaskGroup" | "saving"
  | "taskEmpty" | "taskNew" | "workspaceEmpty" | "workspaceRetry" | "workspaceLoading" | "workspaceEmptyDirectory"
  | "memoryEventCenter" | "memoryRecovery" | "newCodexSession" | "newHanliConversation" | "newNangongConversation" | "newLinghuConversation";

const CONVERSATION_FIXED_UI_TEXT: Record<LocaleValue, Record<`conversation${string}`, string>> = {
  "zh-CN": { conversationReady: "Codex harness 已连接", conversationPlaceholder: "输入代码、调查或修改任务（可粘贴截图）", conversationScreenshot: "截取当前屏幕", conversationHiddenScreenshot: "隐藏 AI Desktop 后截图", conversationOpenSettings: "打开系统设置", conversationAutomaticTest: "自动测试", conversationChecking: "正在检查自动测试环境…", conversationReadyTest: "自动测试环境已就绪", conversationBlocked: "自动测试开启失败", conversationEmptyTitle: "今天要构建什么？", conversationRestart: "重启 AI Desktop", conversationConfirmBeforeContinue: "继续前需要确认", conversationTrustHint: "可只允许本次；只有选择“允许并信任”，相同项目和命令下次才会自动允许。", conversationDecline: "拒绝", conversationAccept: "仅允许本次", conversationAcceptAndTrust: "允许并信任", conversationOther: "其他", conversationInputPlaceholder: "请输入答案", conversationConfirmed: "已确认", conversationConfirming: "正在确认…", conversationConfirm: "确认", conversationCollaborationStatus: "协作任务状态", conversationSystem: "系统", conversationRetryTest: "重新测试", conversationContinue: "继续执行", conversationWaitingHandler: "等待分配负责人", conversationBlockedReason: "当前卡点", conversationTaskDetails: "任务详细 · {name}", conversationCurrentHandler: "当前负责人", conversationStageAnalysis: "技术分析", conversationStageExecution: "执行", conversationStageRecovery: "令狐修复", conversationStageIntegration: "统一测试", conversationRecoverTask: "发现上次未完成的任务", conversationDiscardTask: "放弃任务", conversationBackgroundTask: "任务正在后台执行，完成后将继续处理等待队列。", conversationQueue: "等待队列", conversationSupplementTask: "补充到当前任务", conversationRemove: "移除", conversationInputTools: "输入工具栏", conversationPendingCount: "待发送 {count}", conversationStop: "停止当前任务", conversationSend: "发送", conversationQueueSend: "排队发送", conversationSending: "发送中", conversationSendFailed: "发送失败", conversationSubmitFailed: "无法提交协同任务。", conversationQueued: "消息已进入等待队列。", conversationConfirmationQuestions: "待确认问题", conversationAssistantHeader: "CODEX", conversationUserHeader: "你", conversationUserSendingHeader: "你 · 发送中", conversationUserFailedHeader: "你 · 发送失败", conversationLocalCodexFallback: "桌面版本会在这里返回本地 Codex 的结果。" },
  ja: { conversationReady: "Codex harness 接続済み", conversationPlaceholder: "コード、調査、変更内容を入力（画像を貼り付け可能）", conversationScreenshot: "現在の画面をキャプチャ", conversationHiddenScreenshot: "AI Desktop を隠してキャプチャ", conversationOpenSettings: "システム設定を開く", conversationAutomaticTest: "自動テスト", conversationChecking: "自動テスト環境を確認中…", conversationReadyTest: "自動テスト環境の準備ができました", conversationBlocked: "自動テストを開始できません", conversationEmptyTitle: "何を作りますか？", conversationRestart: "AI Desktop を再起動", conversationConfirmBeforeContinue: "続行前の確認", conversationTrustHint: "今回だけ許可するか、同じプロジェクトの同じコマンドを今後も許可するか選択してください。", conversationDecline: "拒否", conversationAccept: "今回だけ許可", conversationAcceptAndTrust: "許可して信頼", conversationOther: "その他", conversationInputPlaceholder: "回答を入力", conversationConfirmed: "確認済み", conversationConfirming: "送信中…", conversationConfirm: "確認", conversationCollaborationStatus: "協同タスク", conversationSystem: "システム", conversationRetryTest: "再テスト", conversationContinue: "続行", conversationWaitingHandler: "担当者待ち", conversationBlockedReason: "停止理由", conversationTaskDetails: "タスク詳細 · {name}", conversationCurrentHandler: "現在の担当", conversationStageAnalysis: "技術分析", conversationStageExecution: "実行", conversationStageRecovery: "修復", conversationStageIntegration: "統合テスト", conversationRecoverTask: "前回未完了のタスクがあります", conversationDiscardTask: "タスクを破棄", conversationBackgroundTask: "タスクはバックグラウンドで実行中です。完了後に待機キューを処理します。", conversationQueue: "待機キュー", conversationSupplementTask: "現在のタスクに追加", conversationRemove: "削除", conversationInputTools: "入力ツールバー", conversationPendingCount: "送信待ち {count}", conversationStop: "現在のタスクを停止", conversationSend: "送信", conversationQueueSend: "キューに追加", conversationSending: "送信中", conversationSendFailed: "送信失敗", conversationSubmitFailed: "協同タスクを送信できません。", conversationQueued: "メッセージは待機キューに入りました。", conversationConfirmationQuestions: "確認事項", conversationAssistantHeader: "CODEX", conversationUserHeader: "あなた", conversationUserSendingHeader: "あなた · 送信中", conversationUserFailedHeader: "あなた · 送信失敗", conversationLocalCodexFallback: "デスクトップ版でローカル Codex に接続します。" },
  en: { conversationReady: "Codex harness connected", conversationPlaceholder: "Enter code, research, or a change request (images can be pasted)", conversationScreenshot: "Capture current screen", conversationHiddenScreenshot: "Hide AI Desktop and capture", conversationOpenSettings: "Open system settings", conversationAutomaticTest: "Automated test", conversationChecking: "Checking the automated test environment…", conversationReadyTest: "Automated test environment is ready", conversationBlocked: "Could not start automated testing", conversationEmptyTitle: "What would you like to build?", conversationRestart: "Restart AI Desktop", conversationConfirmBeforeContinue: "Confirmation required before continuing", conversationTrustHint: "Allow this time only, or trust the same command in this project for future runs.", conversationDecline: "Decline", conversationAccept: "Allow this time", conversationAcceptAndTrust: "Allow and trust", conversationOther: "Other", conversationInputPlaceholder: "Enter an answer", conversationConfirmed: "Confirmed", conversationConfirming: "Confirming…", conversationConfirm: "Confirm", conversationCollaborationStatus: "Collaboration task status", conversationSystem: "System", conversationRetryTest: "Retry test", conversationContinue: "Continue", conversationWaitingHandler: "Waiting for an assignee", conversationBlockedReason: "Current blocker", conversationTaskDetails: "Task details · {name}", conversationCurrentHandler: "Current handler", conversationStageAnalysis: "Technical analysis", conversationStageExecution: "Execution", conversationStageRecovery: "Repair", conversationStageIntegration: "Unified test", conversationRecoverTask: "An unfinished task was found", conversationDiscardTask: "Discard task", conversationBackgroundTask: "The task is running in the background. The waiting queue will continue afterward.", conversationQueue: "Waiting queue", conversationSupplementTask: "Add to current task", conversationRemove: "Remove", conversationInputTools: "Input tools", conversationPendingCount: "Pending {count}", conversationStop: "Stop current task", conversationSend: "Send", conversationQueueSend: "Queue send", conversationSending: "Sending", conversationSendFailed: "Send failed", conversationSubmitFailed: "Could not submit the collaboration task.", conversationQueued: "Message added to the waiting queue.", conversationConfirmationQuestions: "Confirmation questions", conversationAssistantHeader: "CODEX", conversationUserHeader: "YOU", conversationUserSendingHeader: "YOU · Sending", conversationUserFailedHeader: "YOU · Send failed", conversationLocalCodexFallback: "The desktop app will return the local Codex result here." },
};

const COLLABORATION_FIXED_UI_TEXT: Record<LocaleValue, Record<string, string>> = {
  "zh-CN": { collaborationMemberIdle: "空闲", collaborationMemberConversation: "会话中", collaborationMemberAssigned: "已分配", collaborationMemberWorking: "正在执行", collaborationMemberRetiring: "正在关闭连接", collaborationMemberRecovering: "等待恢复", collaborationMemberDraining: "等待退出", collaborationMemberOffline: "离线", collaborationPhaseAnalyzing: "技术分析中", collaborationPhasePlanning: "整理方案中", collaborationPhaseImplementing: "执行修改中", collaborationPhaseVerifying: "自检中", collaborationPhaseFinalizing: "整理结果中", collaborationPhaseReady: "等待下一步", collaborationPhaseBlocked: "已阻塞", collaborationPhaseFailed: "处理失败", collaborationTaskQueuedExecutor: "等待执行人", collaborationTaskPreparingWorktree: "准备独立版本", collaborationTaskAnalyzing: "技术分析", collaborationTaskExecuting: "执行修改", collaborationTaskRepairingExecution: "令狐修复执行问题", collaborationTaskReturnedNangong: "已返回南宫婉", collaborationTaskReadyIntegration: "本轮已封存", collaborationTaskQueuedIntegration: "已进入测试批次", collaborationTaskIntegrating: "正在集成", collaborationTaskUnifiedTesting: "令狐老祖正在统一测试", collaborationTaskAwaitingRestart: "等待重启确认", collaborationTaskTestFailed: "统一测试失败", collaborationTaskIntegrated: "统一测试通过", collaborationTaskBlocked: "已阻塞", collaborationTaskRecovering: "等待恢复", collaborationTaskCancelled: "已取消", collaborationPlanReady: "技术分析完成", collaborationExecutionAssigned: "已分配", collaborationExecutionAnalyzing: "分析中", collaborationExecutionExecuting: "执行中", collaborationExecutionVerified: "代码已验证", collaborationExecutionTransferred: "已转交", collaborationExecutionBlocked: "已阻塞", collaborationExecutionCancelled: "已取消", collaborationAwaitingConfirmation: "等待你确认", collaborationInternalDeliberating: "内部研讨中", collaborationInquiryRecovering: "等待恢复排查", collaborationInquiryBlocked: "排查受阻", collaborationInquiryVerifying: "只读核实中", collaborationInquiryPreparing: "准备排查中", collaborationInquiryWaiting: "等待核实中", collaborationInquiryAssessing: "研判结果中", collaborationInquiryExplaining: "整理结论中", collaborationInquiryInvestigating: "排查中", collaborationStateUnavailable: "状态暂未更新", collaborationStateSyncing: "正在同步" },
  ja: { collaborationMemberIdle: "待機", collaborationMemberConversation: "会話中", collaborationMemberAssigned: "割当済み", collaborationMemberWorking: "実行中", collaborationMemberRetiring: "接続終了中", collaborationMemberRecovering: "復旧待ち", collaborationMemberDraining: "終了待ち", collaborationMemberOffline: "オフライン", collaborationPhaseAnalyzing: "技術分析中", collaborationPhasePlanning: "提案整理中", collaborationPhaseImplementing: "変更実行中", collaborationPhaseVerifying: "自己検証中", collaborationPhaseFinalizing: "結果整理中", collaborationPhaseReady: "次の操作待ち", collaborationPhaseBlocked: "ブロック", collaborationPhaseFailed: "処理失敗", collaborationTaskQueuedExecutor: "実行者待ち", collaborationTaskPreparingWorktree: "独立版を準備", collaborationTaskAnalyzing: "技術分析", collaborationTaskExecuting: "変更実行中", collaborationTaskRepairingExecution: "令狐が実行問題を修復中", collaborationTaskReturnedNangong: "南宮婉へ返却済み", collaborationTaskReadyIntegration: "ラウンド確定済み", collaborationTaskQueuedIntegration: "テストキュー", collaborationTaskIntegrating: "統合中", collaborationTaskUnifiedTesting: "令狐が統合テスト中", collaborationTaskAwaitingRestart: "再起動確認待ち", collaborationTaskTestFailed: "統合テスト失敗", collaborationTaskIntegrated: "統合テスト合格", collaborationTaskBlocked: "ブロック", collaborationTaskRecovering: "復旧待ち", collaborationTaskCancelled: "キャンセル", collaborationPlanReady: "技術分析完了", collaborationExecutionAssigned: "割当済み", collaborationExecutionAnalyzing: "分析中", collaborationExecutionExecuting: "実行中", collaborationExecutionVerified: "コード検証済み", collaborationExecutionTransferred: "引継ぎ済み", collaborationExecutionBlocked: "ブロック", collaborationExecutionCancelled: "キャンセル", collaborationAwaitingConfirmation: "確認待ち", collaborationInternalDeliberating: "内部検討中", collaborationInquiryRecovering: "調査再開待ち", collaborationInquiryBlocked: "調査ブロック", collaborationInquiryVerifying: "読取検証中", collaborationInquiryPreparing: "調査準備中", collaborationInquiryWaiting: "検証待ち", collaborationInquiryAssessing: "結果判定中", collaborationInquiryExplaining: "結論整理中", collaborationInquiryInvestigating: "調査中", collaborationStateUnavailable: "状態は未更新です", collaborationStateSyncing: "同期中" },
  en: { collaborationMemberIdle: "Idle", collaborationMemberConversation: "In conversation", collaborationMemberAssigned: "Assigned", collaborationMemberWorking: "Working", collaborationMemberRetiring: "Closing connection", collaborationMemberRecovering: "Awaiting recovery", collaborationMemberDraining: "Awaiting exit", collaborationMemberOffline: "Offline", collaborationPhaseAnalyzing: "Analyzing", collaborationPhasePlanning: "Preparing plan", collaborationPhaseImplementing: "Applying changes", collaborationPhaseVerifying: "Verifying", collaborationPhaseFinalizing: "Preparing results", collaborationPhaseReady: "Awaiting next step", collaborationPhaseBlocked: "Blocked", collaborationPhaseFailed: "Failed", collaborationTaskQueuedExecutor: "Awaiting executor", collaborationTaskPreparingWorktree: "Preparing isolated version", collaborationTaskAnalyzing: "Technical analysis", collaborationTaskExecuting: "Applying changes", collaborationTaskRepairingExecution: "Repairing execution", collaborationTaskReturnedNangong: "Returned to Nangong Wan", collaborationTaskReadyIntegration: "Round archived", collaborationTaskQueuedIntegration: "Queued for testing", collaborationTaskIntegrating: "Integrating", collaborationTaskUnifiedTesting: "Running unified tests", collaborationTaskAwaitingRestart: "Awaiting restart confirmation", collaborationTaskTestFailed: "Unified test failed", collaborationTaskIntegrated: "Unified test passed", collaborationTaskBlocked: "Blocked", collaborationTaskRecovering: "Awaiting recovery", collaborationTaskCancelled: "Cancelled", collaborationPlanReady: "Technical analysis complete", collaborationExecutionAssigned: "Assigned", collaborationExecutionAnalyzing: "Analyzing", collaborationExecutionExecuting: "Executing", collaborationExecutionVerified: "Code verified", collaborationExecutionTransferred: "Transferred", collaborationExecutionBlocked: "Blocked", collaborationExecutionCancelled: "Cancelled", collaborationAwaitingConfirmation: "Awaiting your confirmation", collaborationInternalDeliberating: "Internal deliberation", collaborationInquiryRecovering: "Awaiting investigation recovery", collaborationInquiryBlocked: "Investigation blocked", collaborationInquiryVerifying: "Read-only verification", collaborationInquiryPreparing: "Preparing investigation", collaborationInquiryWaiting: "Awaiting verification", collaborationInquiryAssessing: "Assessing results", collaborationInquiryExplaining: "Preparing conclusion", collaborationInquiryInvestigating: "Investigating", collaborationStateUnavailable: "Status is not updated", collaborationStateSyncing: "Syncing" },
};

const FIXED_UI_TEXT: Record<LocaleValue, Partial<Record<FixedUiTextKey, string>>> = {
  "zh-CN": { ...CONVERSATION_FIXED_UI_TEXT["zh-CN"], ...COLLABORATION_FIXED_UI_TEXT["zh-CN"],
    language: "语言", languageSaving: "正在保存语言设置…", languageSaveFailed: "无法保存语言设置，请重试。",
    retry: "重试", dismiss: "关闭", settingsReadRecovered: "无法读取已保存的设置，已暂时使用简体中文。",
    screenshotSettingsReadTitle: "无法读取语言设置", screenshotSettingsReadDetail: "截图窗口暂时使用简体中文。",
    close: "关闭", technicalDetails: "技术详情", loadingScreenshot: "正在载入截图…", missingText: "缺少固定界面文案",
    managedModeConversation: "理解意图", managedModeRequirement: "分析方案", managedModeTask: "执行修改", managedModeTest: "验证结果",
    managedStageConfirmIntent: "就是这意思", managedStageExecutePlan: "按这个方案执行", managedStageTest: "测试一下", managedStageRetest: "重新测试",
    managedStageReanalyze: "重新分析需求", managedStageRerun: "重新执行",
    streamProcess: "执行过程", streamActivityCount: "{count} 项", streamChangedFiles: "已涉及 {count} 个文件",
    streamActivityReasoning: "正在分析", streamActivityCommandExecution: "执行命令", streamActivityCommandPolicy: "执行策略",
    streamActivityFileChange: "修改文件", streamActivityMcpToolCall: "调用工具", streamActivityDynamicToolCall: "执行工具",
    streamActivityCollabToolCall: "协作处理", streamActivityWebSearch: "搜索网页", streamActivityImageView: "查看图片",
    streamActivityContextCompaction: "整理会话", streamActivityAgentMessage: "生成回答", streamUnknownActivity: "未知执行项",
    streamStarting: "正在启动 Codex…", streamInProgress: "Codex 正在处理…", streamPlanning: "正在更新计划…",
    streamReasoning: "正在分析…", streamResponding: "正在生成回答…", streamCommandExecution: "正在执行命令…", streamFileChange: "正在修改文件…",
    streamInterrupted: "已中断", streamFailed: "执行失败", streamCompleted: "已完成", streamConversationCompleted: "意图分析完成",
    streamRequirementCompleted: "需求分析完成", streamTaskCompleted: "执行与代码验证完成", streamTestCompleted: "测试完成",
    screenshotSelect: "选择截图区域", screenshotSelectHint: "拖动鼠标框选需要截取的区域", screenshotAnnotate: "红色标注", screenshotDone: "完成",
    screenshotPen: "画笔", screenshotRectangle: "方框", screenshotUndo: "撤销", screenshotClear: "清空绘画框",
    screenshotClearConfirm: "确定清空全部红色绘画标注吗？", screenshotCancel: "取消", screenshotBack: "返回", screenshotSaving: "正在保存…",
    screenshotLoadFailed: "无法载入截图。", screenshotSaveFailed: "无法保存截图。", screenshotWindowControl: "最大化或还原窗口",
    screenshotCapturedScreen: "已捕获的屏幕", screenshotResizeAnnotation: "调整红框-{handle}",
    workspaceFilePreview: "文件预览", workspaceCloseFilePreview: "关闭文件预览", workspaceCopyContent: "复制完整内容",
    workspaceContentCopied: "已复制文件内容。", workspaceCopyFailed: "无法复制文件内容。",
    developerTitle: "Developer", developerSettings: "连接与执行设置", developerSettingsOpen: "打开连接与执行设置", developerSettingsClose: "关闭连接与执行设置",
    workspaceList: "工作区", workspaceAdd: "添加工作区", workspacePrimary: "主目录", workspaceMakePrimary: "设为主目录", workspaceRemove: "移除", workspaceRemoveConfirm: "确定从工作区列表移除“{name}”吗？不会删除磁盘中的真实目录。", workspaceMinimum: "至少保留一个工作区",
    sandboxReadOnly: "只读", sandboxWrite: "工作区写入", sandboxReadOnlyTip: "当前只读", sandboxWriteTip: "当前可写入", account: "ChatGPT 账号", signedOut: "请先登录 ChatGPT", signOut: "退出登录", signIn: "使用 ChatGPT 登录", browserOpened: "请在浏览器中完成登录", tempFiles: "临时文件", openTemp: "临时目录", clearTemp: "一键清理", clearTempConfirm: "确定清理 AI Desktop temp 中的全部临时文件吗？", trustedCommands: "可信命令", trustedCommandsHint: "相同项目和命令下次将自动允许。", clearTrustedCommands: "清除全部信任", clearTrustedConfirm: "确定清除全部项目可信命令吗？", auditLogs: "业务日志", openAuditLogs: "打开日志目录", noAuditTask: "暂无任务记录", attachment: "图片附件", automaticTestTriggered: "自动测试", screenSourceUnavailable: "无法读取屏幕来源，请检查屏幕录制权限后重试。",
    memoryDatabaseDisabledTitle: "AI Memory 数据库已停用", memoryDatabaseDisabledDetail: "请恢复数据库后重新启动。", sidebarResize: "调整侧栏宽度",
    testDataTitle: "测试数据", testDataSummary: "数据库中的测试专题、任务、审批、事件和运行状态", testDataDetail: "保留人物对话、训练记忆、登录、设置、工作区、规则和源码；完成后自动重启应用。", testDataAction: "一键清空测试数据", testDataBusy: "正在清空…", testDataConfirm: "确定一键清空 AI Desktop 内部的测试运行数据吗？此操作不可撤销。旧审批参考也会被清除，之后不能再用于建议或恢复。不会删除人物对话、训练记忆、登录、设置、工作区、可信命令、规则、源码和工程审计文件。", testDataRestart: "确认结果并重启", testDataRestartConfirm: "我已确认本次实际清理结果，现在按受控路径重启应用。是否继续？", testDataResult: "已清除 {count} 条运行记录。", testDataCandidates: "已处理候选分支 {branches} 个、工作树 {worktrees} 个。", testDataClearFailed: "清空测试数据失败。", testDataRestartFailed: "无法启动应用重启。", resetCategoryCollaboration: "协作运行状态", resetCategoryEvolution: "演化运行状态", resetCategoryLinghu: "令狐运行状态", resetCategoryWorkflow: "事件与工作流投影",
    modelDefault: "Codex 默认", modelDefaultLabel: "默认模型", modelRuntimeDownloaded: "校验下载", modelRuntimeBundled: "安装包内置", modelCatalogLoading: "正在读取模型列表…", modelCatalogLoaded: "已读取 {count} 个模型 · Astra{astra}", modelCatalogAstraPresent: "已出现", modelCatalogAstraMissing: "未出现", modelSettingsTitle: "全局模型配置", modelSettingsSummary: "对所有会话与协同任务生效", modelLoading: "正在读取模型…", modelEffort: "推理强度", modelEffortDefault: "模型默认", modelSpeed: "推理速度", modelStandardSpeed: "标准", modelFastSpeed: "快速", modelUnavailable: "已保存的模型当前不可用，请重新选择。", modelSpeedUnavailable: "当前模型不支持快速处理，请切换为标准速度。", modelCatalogFailed: "无法读取模型列表。", settingsSaveFailed: "无法保存全局设置。",
    corpusTitle: "Codex 聊天训练入库", corpusEnabled: "已开启", corpusDisabled: "未开启", corpusDetail: "只将当前 SELPLAT 工作区中已经完成的每轮可见对话入库，排除系统指令、工具输出和文件注入内容。", corpusIngestionPrefix: "自动入库", corpusStart: "开启入库", corpusStop: "停止入库", corpusBackfill: "补齐历史摘要", corpusBackfillBusy: "正在补齐…", corpusBackfillAria: "一键补齐历史 AI 摘要", corpusStopped: "自动入库已停止。",
    auditReasonCount: "{count} 项原因", auditRunning: "运行中", auditCompleted: "已完成", auditPartial: "部分完成", auditFailed: "失败", auditInterrupted: "已中断", reasoningNone: "无", reasoningMinimal: "最小", reasoningLow: "低", reasoningMedium: "中", reasoningHigh: "高", reasoningXhigh: "超高", reasoningMax: "最大", reasoningUltra: "极致", settingsPanelResize: "调整设置面板宽度", settingsPanelResizeRight: "从右侧调整设置面板宽度", settingsPanelResizeReset: "双击恢复默认宽度", languageOptionZhCn: "简体中文", languageOptionJa: "日本語", languageOptionEn: "English", sandbox: "Sandbox", recordUnit: "条",
    sidebarExpand: "展开侧栏", sidebarCollapse: "折叠侧栏", taskExpand: "展开", taskCollapse: "折叠", taskSection: "任务", taskSectionHeading: "任务", operatingMode: "运行模式", operatingSingleConversation: "单会话", operatingCollaboration: "协同模式", collaborationTaskGroup: "任务协作群", saving: "保存中", taskEmpty: "暂无任务记录", taskNew: "新建任务", workspaceEmpty: "暂无已登记工作区。", workspaceRetry: "重试", workspaceLoading: "正在读取…", workspaceEmptyDirectory: "空目录", memoryEventCenter: "统一事件中心", memoryRecovery: "待恢复", newCodexSession: "重新建立一个 Codex 会话", newHanliConversation: "重新建立韩立对话", newNangongConversation: "重新建立南宫婉对话", newLinghuConversation: "重新建立令狐老祖对话",
  },
  ja: { ...CONVERSATION_FIXED_UI_TEXT.ja, ...COLLABORATION_FIXED_UI_TEXT.ja,
    language: "言語", languageSaving: "言語設定を保存しています…", languageSaveFailed: "言語設定を保存できません。もう一度お試しください。",
    retry: "再試行", dismiss: "閉じる", settingsReadRecovered: "保存済みの設定を読み込めないため、一時的に簡体字中国語を使用しています。",
    screenshotSettingsReadTitle: "言語設定を読み込めません", screenshotSettingsReadDetail: "スクリーンショットウィンドウは一時的に簡体字中国語を使用しています。",
    close: "閉じる", technicalDetails: "技術詳細", loadingScreenshot: "スクリーンショットを読み込んでいます…", missingText: "固定画面文言がありません",
    managedModeConversation: "意図を確認", managedModeRequirement: "案を整理", managedModeTask: "変更を実行", managedModeTest: "結果を検証",
    managedStageConfirmIntent: "この意図で合っています", managedStageExecutePlan: "この案で実行", managedStageTest: "テストする", managedStageRetest: "再テスト",
    managedStageReanalyze: "要件を再分析", managedStageRerun: "再実行",
    streamProcess: "実行プロセス", streamActivityCount: "{count} 件", streamChangedFiles: "変更ファイル {count}",
    streamActivityReasoning: "分析中", streamActivityCommandExecution: "コマンド実行", streamActivityCommandPolicy: "実行ポリシー",
    streamActivityFileChange: "ファイル変更", streamActivityMcpToolCall: "ツール呼び出し", streamActivityDynamicToolCall: "ツール実行",
    streamActivityCollabToolCall: "エージェント連携", streamActivityWebSearch: "Web 検索", streamActivityImageView: "画像確認",
    streamActivityContextCompaction: "会話整理", streamActivityAgentMessage: "回答作成", streamUnknownActivity: "不明な実行項目",
    streamStarting: "Codex を開始しています…", streamInProgress: "Codex が処理中…", streamPlanning: "計画を更新しています…",
    streamReasoning: "分析中…", streamResponding: "回答を生成しています…", streamCommandExecution: "コマンドを実行しています…", streamFileChange: "ファイルを変更しています…",
    streamInterrupted: "中断しました", streamFailed: "失敗しました", streamCompleted: "完了しました", streamConversationCompleted: "意図の分析が完了しました",
    streamRequirementCompleted: "要件分析が完了しました", streamTaskCompleted: "実行とコード検証が完了しました", streamTestCompleted: "テストが完了しました",
    screenshotSelect: "範囲を選択", screenshotSelectHint: "ドラッグして切り取る範囲を選択してください", screenshotAnnotate: "赤で注釈", screenshotDone: "完了",
    screenshotPen: "ペン", screenshotRectangle: "四角", screenshotUndo: "元に戻す", screenshotClear: "描画をすべて消去",
    screenshotClearConfirm: "すべての赤い注釈を消去しますか？", screenshotCancel: "キャンセル", screenshotBack: "戻る", screenshotSaving: "保存中…",
    screenshotLoadFailed: "スクリーンショットを読み込めません。", screenshotSaveFailed: "スクリーンショットを保存できません。", screenshotWindowControl: "ウィンドウを最大化または復元",
    screenshotCapturedScreen: "取得した画面", screenshotResizeAnnotation: "注釈を調整 {handle}",
    workspaceFilePreview: "ファイルプレビュー", workspaceCloseFilePreview: "ファイルプレビューを閉じる", workspaceCopyContent: "内容をコピー",
    workspaceContentCopied: "ファイル内容をコピーしました。", workspaceCopyFailed: "ファイル内容をコピーできませんでした。",
    developerTitle: "Developer", developerSettings: "接続と実行設定", developerSettingsOpen: "接続と実行設定を開く", developerSettingsClose: "接続と実行設定を閉じる", workspaceList: "WORKSPACES", workspaceAdd: "ワークスペースを追加", workspacePrimary: "メイン", workspaceMakePrimary: "メインに設定", workspaceRemove: "削除", workspaceRemoveConfirm: "ワークスペース一覧から「{name}」を削除しますか？ディスク上のフォルダーは削除されません。", workspaceMinimum: "ワークスペースを1つ以上残してください", sandboxReadOnly: "読み取り専用", sandboxWrite: "ワークスペース書き込み", sandboxReadOnlyTip: "現在は読み取り専用", sandboxWriteTip: "現在は書き込み可能", account: "ChatGPT アカウント", signedOut: "ChatGPT にログインしてください", signOut: "ログアウト", signIn: "ChatGPT でログイン", browserOpened: "ブラウザーでログインを完了してください", tempFiles: "一時ファイル", openTemp: "一時フォルダーを開く", clearTemp: "すべて消去", clearTempConfirm: "AI Desktop の一時ファイルをすべて削除しますか？", trustedCommands: "信頼済みコマンド", trustedCommandsHint: "同じプロジェクトとコマンドは次回から自動的に許可されます。", clearTrustedCommands: "信頼をすべて解除", clearTrustedConfirm: "登録済みの信頼コマンドをすべて解除しますか？", auditLogs: "業務ログ", openAuditLogs: "ログフォルダーを開く", noAuditTask: "タスク履歴はまだありません", attachment: "画像添付", automaticTestTriggered: "自動テスト", screenSourceUnavailable: "画面ソースを読み取れません。画面収録の権限を確認してから再試行してください。",
    memoryDatabaseDisabledTitle: "AI Memory データベースは停止中です", memoryDatabaseDisabledDetail: "設定、移行、または整合性の問題を確認し、元のデータベースを復旧してから再起動してください。", sidebarResize: "サイドバーの幅", testDataTitle: "テストデータ", testDataSummary: "データベース内のテストトピック、タスク、承認、イベント、実行状態", testDataDetail: "人物の会話、学習メモリ、ログイン、設定、ワークスペース、ルール、ソースコードは保持されます。完了後にアプリを再起動します。", testDataAction: "テストデータを一括消去", testDataBusy: "消去中…", testDataConfirm: "AI Desktop 内部のテスト実行データを消去しますか？この操作は元に戻せません。古い承認参照も消去され、提案や復元には使用できなくなります。人物の会話、学習メモリ、ログイン、設定、ワークスペース、信頼済みコマンド、ルール、ソースコード、監査ファイルは削除されません。", testDataRestart: "結果を確認して再起動", testDataRestartConfirm: "表示されている消去結果を確認しました。現在のアプリを再起動しますか？", testDataResult: "実行記録を {count} 件消去しました。", testDataCandidates: "候補ブランチ {branches} 件・Worktree {worktrees} 件を処理しました。", testDataClearFailed: "テストデータを消去できませんでした。", testDataRestartFailed: "再起動を開始できませんでした。", resetCategoryCollaboration: "協同実行状態", resetCategoryEvolution: "進化実行状態", resetCategoryLinghu: "令狐実行状態", resetCategoryWorkflow: "イベントとワークフロー投影",
    modelDefault: "Codex の既定値", modelDefaultLabel: "既定モデル", modelRuntimeDownloaded: "検証済みダウンロード", modelRuntimeBundled: "インストール済みパッケージ", modelCatalogLoading: "モデル一覧を読み込み中…", modelCatalogLoaded: "モデル一覧を取得しました（{count}件）・Astra {astra}", modelCatalogAstraPresent: "あり", modelCatalogAstraMissing: "なし", modelSettingsTitle: "グローバルモデル設定", modelSettingsSummary: "すべての会話と協同タスクに適用", modelLoading: "モデルを読み込み中…", modelEffort: "推論の強度", modelEffortDefault: "モデルの既定値", modelSpeed: "推論速度", modelStandardSpeed: "標準", modelFastSpeed: "高速", modelUnavailable: "保存済みモデルは現在利用できません。別のモデルを選択してください。", modelSpeedUnavailable: "選択中のモデルは高速処理に対応していません。標準速度へ変更してください。", modelCatalogFailed: "モデル一覧を取得できません。", settingsSaveFailed: "設定を保存できません。", corpusTitle: "Codex 会話の学習登録", corpusEnabled: "有効", corpusDisabled: "無効", corpusDetail: "現在の SELPLAT ワークスペースに属する完了済みの各ターンだけを登録し、システム指示・ツール出力・ファイル注入は除外します。", corpusIngestionPrefix: "自動登録", corpusStart: "登録を開始", corpusStop: "登録を停止", corpusBackfill: "履歴を一括補完", corpusBackfillBusy: "補完中…", corpusBackfillAria: "履歴の AI 要約を一括補完", corpusStopped: "自動登録は停止しています。", auditReasonCount: "{count} 件の理由", auditRunning: "実行中", auditCompleted: "完了", auditPartial: "一部完了", auditFailed: "失敗", auditInterrupted: "中断", reasoningNone: "なし", reasoningMinimal: "最小", reasoningLow: "低", reasoningMedium: "中", reasoningHigh: "高", reasoningXhigh: "最高", reasoningMax: "最大", reasoningUltra: "極限", settingsPanelResize: "設定パネルの幅を調整", settingsPanelResizeRight: "右側から設定パネルの幅を調整", settingsPanelResizeReset: "ダブルクリックで既定の幅に戻す", languageOptionZhCn: "简体中文", languageOptionJa: "日本語", languageOptionEn: "English", sandbox: "Sandbox", recordUnit: "件",
    sidebarExpand: "サイドバーを展開", sidebarCollapse: "サイドバーを折りたたむ", taskExpand: "展開", taskCollapse: "折りたたむ", taskSection: "タスク", taskSectionHeading: "TASKS", operatingMode: "実行モード", operatingSingleConversation: "単一会話", operatingCollaboration: "協同", collaborationTaskGroup: "タスク協同グループ", saving: "保存中", taskEmpty: "タスク履歴はまだありません", taskNew: "新しいタスク", workspaceEmpty: "登録済みのワークスペースはありません。", workspaceRetry: "再試行", workspaceLoading: "読み込み中…", workspaceEmptyDirectory: "空のフォルダー", memoryEventCenter: "統合イベントセンター", memoryRecovery: "要復旧", newCodexSession: "Codex セッションを新しく作り直す", newHanliConversation: "韓立の会話を新しく作り直す", newNangongConversation: "南宮婉の会話を新しく作り直す", newLinghuConversation: "令狐老祖の会話を新しく作り直す",
  },
  en: { ...CONVERSATION_FIXED_UI_TEXT.en, ...COLLABORATION_FIXED_UI_TEXT.en,
    language: "Language", languageSaving: "Saving language settings…", languageSaveFailed: "Language settings could not be saved. Please try again.",
    retry: "Retry", dismiss: "Dismiss", settingsReadRecovered: "Saved settings could not be read. Simplified Chinese is in use temporarily.",
    screenshotSettingsReadTitle: "Language settings could not be read", screenshotSettingsReadDetail: "The screenshot window is using Simplified Chinese temporarily.",
    close: "Close", technicalDetails: "Technical details", loadingScreenshot: "Loading screenshot…", missingText: "Missing fixed UI text",
    managedModeConversation: "Understand intent", managedModeRequirement: "Analyze plan", managedModeTask: "Apply changes", managedModeTest: "Verify results",
    managedStageConfirmIntent: "This is what I mean", managedStageExecutePlan: "Apply this plan", managedStageTest: "Run tests", managedStageRetest: "Run tests again",
    managedStageReanalyze: "Analyze requirements again", managedStageRerun: "Run again",
    streamProcess: "Execution process", streamActivityCount: "{count} items", streamChangedFiles: "{count} changed files",
    streamActivityReasoning: "Analyzing", streamActivityCommandExecution: "Running command", streamActivityCommandPolicy: "Command policy",
    streamActivityFileChange: "Changing files", streamActivityMcpToolCall: "Calling tool", streamActivityDynamicToolCall: "Running tool",
    streamActivityCollabToolCall: "Collaborating", streamActivityWebSearch: "Searching the web", streamActivityImageView: "Viewing image",
    streamActivityContextCompaction: "Compacting conversation", streamActivityAgentMessage: "Writing response", streamUnknownActivity: "Unknown execution item",
    streamStarting: "Starting Codex…", streamInProgress: "Codex is working…", streamPlanning: "Updating plan…",
    streamReasoning: "Analyzing…", streamResponding: "Writing response…", streamCommandExecution: "Running command…", streamFileChange: "Changing files…",
    streamInterrupted: "Interrupted", streamFailed: "Execution failed", streamCompleted: "Completed", streamConversationCompleted: "Intent analysis completed",
    streamRequirementCompleted: "Requirements analysis completed", streamTaskCompleted: "Changes and code validation completed", streamTestCompleted: "Tests completed",
    screenshotSelect: "Select area", screenshotSelectHint: "Drag to select the area to capture", screenshotAnnotate: "Annotate in red", screenshotDone: "Done",
    screenshotPen: "Pen", screenshotRectangle: "Rectangle", screenshotUndo: "Undo", screenshotClear: "Clear annotations",
    screenshotClearConfirm: "Clear all red annotations?", screenshotCancel: "Cancel", screenshotBack: "Back", screenshotSaving: "Saving…",
    screenshotLoadFailed: "Screenshot image could not be loaded.", screenshotSaveFailed: "Screenshot could not be saved.", screenshotWindowControl: "Maximize or restore window",
    screenshotCapturedScreen: "Captured screen", screenshotResizeAnnotation: "Resize annotation {handle}",
    workspaceFilePreview: "File preview", workspaceCloseFilePreview: "Close file preview", workspaceCopyContent: "Copy full content",
    workspaceContentCopied: "File content copied.", workspaceCopyFailed: "File content could not be copied.",
    developerTitle: "Developer", developerSettings: "Connection and execution settings", developerSettingsOpen: "Open connection and execution settings", developerSettingsClose: "Close connection and execution settings", workspaceList: "WORKSPACES", workspaceAdd: "Add workspace", workspacePrimary: "Primary", workspaceMakePrimary: "Make primary", workspaceRemove: "Remove", workspaceRemoveConfirm: "Remove “{name}” from the workspace list? Its folder will remain on disk.", workspaceMinimum: "Keep at least one workspace", sandboxReadOnly: "Read only", sandboxWrite: "Workspace write", sandboxReadOnlyTip: "Currently read only", sandboxWriteTip: "Currently writable", account: "ChatGPT account", signedOut: "Sign in to ChatGPT first", signOut: "Sign out", signIn: "Sign in with ChatGPT", browserOpened: "Finish signing in in your browser", tempFiles: "Temporary files", openTemp: "Open temporary folder", clearTemp: "Clear all", clearTempConfirm: "Clear all temporary AI Desktop files?", trustedCommands: "Trusted commands", trustedCommandsHint: "The same project and command will be allowed automatically next time.", clearTrustedCommands: "Clear all trust", clearTrustedConfirm: "Clear all trusted project commands?", auditLogs: "Audit logs", openAuditLogs: "Open log folder", noAuditTask: "No task history yet", attachment: "Image attachment", automaticTestTriggered: "Automated test", screenSourceUnavailable: "Screen sources could not be read. Check Screen Recording permission and try again.",
    memoryDatabaseDisabledTitle: "AI Memory database is disabled", memoryDatabaseDisabledDetail: "Restore the database, then restart.", sidebarResize: "Resize sidebar", testDataTitle: "Test data", testDataSummary: "Test topics, tasks, approvals, events, and run state in the database", testDataDetail: "Persona conversations, training memory, sign-in, settings, workspaces, rules, and source code are retained. The app restarts when finished.", testDataAction: "Clear test data", testDataBusy: "Clearing…", testDataConfirm: "Clear AI Desktop test run data? This cannot be undone. Old approval references will also be cleared, while persona conversations, training memory, sign-in, settings, workspaces, trusted commands, rules, source code, and audit files remain.", testDataRestart: "Confirm results and restart", testDataRestartConfirm: "I have checked the cleanup results. Restart the app now?", testDataResult: "Cleared {count} run records.", testDataCandidates: "Processed {branches} candidate branches and {worktrees} worktrees.", testDataClearFailed: "Could not clear test data.", testDataRestartFailed: "Could not start the app restart.", resetCategoryCollaboration: "Collaboration runs", resetCategoryEvolution: "Evolution runs", resetCategoryLinghu: "Linghu runs", resetCategoryWorkflow: "Events and workflow projections",
    modelDefault: "Codex default", modelDefaultLabel: "Default model", modelRuntimeDownloaded: "Verified download", modelRuntimeBundled: "Bundled package", modelCatalogLoading: "Loading model list…", modelCatalogLoaded: "Loaded {count} models · Astra {astra}", modelCatalogAstraPresent: "available", modelCatalogAstraMissing: "unavailable", modelSettingsTitle: "Global model settings", modelSettingsSummary: "Applies to every conversation and collaboration task", modelLoading: "Loading models…", modelEffort: "Reasoning effort", modelEffortDefault: "Model default", modelSpeed: "Reasoning speed", modelStandardSpeed: "Standard", modelFastSpeed: "Fast", modelUnavailable: "The saved model is unavailable. Select another model.", modelSpeedUnavailable: "The current model does not support fast processing. Switch to standard speed.", modelCatalogFailed: "Model list could not be read.", settingsSaveFailed: "Global settings could not be saved.", corpusTitle: "Codex conversation training ingestion", corpusEnabled: "Enabled", corpusDisabled: "Disabled", corpusDetail: "Only completed visible turns in the current SELPLAT workspace are ingested. System instructions, tool output, and file injection are excluded.", corpusIngestionPrefix: "Automatic ingestion", corpusStart: "Start ingestion", corpusStop: "Stop ingestion", corpusBackfill: "Backfill history summaries", corpusBackfillBusy: "Backfilling…", corpusBackfillAria: "Backfill historical AI summaries", corpusStopped: "Automatic ingestion is stopped.", auditReasonCount: "{count} reasons", auditRunning: "Running", auditCompleted: "Completed", auditPartial: "Partially completed", auditFailed: "Failed", auditInterrupted: "Interrupted", reasoningNone: "None", reasoningMinimal: "Minimal", reasoningLow: "Low", reasoningMedium: "Medium", reasoningHigh: "High", reasoningXhigh: "Extra high", reasoningMax: "Maximum", reasoningUltra: "Ultra", settingsPanelResize: "Resize settings panel", settingsPanelResizeRight: "Resize settings panel from the right", settingsPanelResizeReset: "Double-click to restore the default width", languageOptionZhCn: "Simplified Chinese", languageOptionJa: "Japanese", languageOptionEn: "English", sandbox: "Sandbox", recordUnit: "records",
    sidebarExpand: "Expand sidebar", sidebarCollapse: "Collapse sidebar", taskExpand: "Expand", taskCollapse: "Collapse", taskSection: "Tasks", taskSectionHeading: "TASKS", operatingMode: "Execution mode", operatingSingleConversation: "Single conversation", operatingCollaboration: "Collaboration", collaborationTaskGroup: "Task collaboration group", saving: "Saving", taskEmpty: "No task history yet", taskNew: "New task", workspaceEmpty: "No registered workspaces.", workspaceRetry: "Retry", workspaceLoading: "Loading…", workspaceEmptyDirectory: "Empty folder", memoryEventCenter: "Unified event center", memoryRecovery: "Recovery required", newCodexSession: "Start a new Codex session", newHanliConversation: "Start a new Hanli conversation", newNangongConversation: "Start a new Nangong Wan conversation", newLinghuConversation: "Start a new Linghu Ancestor conversation",
  },
};

const CONTROLLED_MISSING_TEXT = "缺少固定界面文案";

/** 按当前语言、简体中文和受控诊断顺序解析固定界面文案。 */
export function fixedUiText(locale: LocaleValue, key: FixedUiTextKey): string {
  return resolveFixedUiText(FIXED_UI_TEXT, locale, key);
}

/** 为资源回归测试和后续分域资源加载提供可注入的同一回退顺序。 */
export function resolveFixedUiText(
  catalog: Partial<Record<LocaleValue, Partial<Record<FixedUiTextKey, string>>>>,
  locale: LocaleValue | string,
  key: FixedUiTextKey | string,
): string {
  const entry = key as FixedUiTextKey;
  return catalog[locale as LocaleValue]?.[entry]
    || catalog["zh-CN"]?.[entry]
    || `[${catalog["zh-CN"]?.missingText || CONTROLLED_MISSING_TEXT}: ${key}]`;
}
