-- CommonSequenceSegment 用于保存 MDA 按模块缓存主键号段的公共配置，当前主要为连接配置表生成唯一主键。
CREATE TABLE IF NOT EXISTS CommonSequenceSegment (
    -- id 作为号段配置记录标识，供后台维护和后续扩展稳定引用。
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- tenantId 表达当前号段配置归属的租户边界，便于多租户环境隔离不同租户的主键规则。
    tenantId BIGINT NOT NULL,
    -- lastOperateUserId 记录最近维护该号段配置的用户标识，便于追踪最后维护责任人。
    lastOperateUserId BIGINT NOT NULL,
    -- seqCode 保存模块号段编码，发号服务按该编码定位配置，当前使用 MdaConnectionProfileId。
    seqCode VARCHAR(64) NOT NULL UNIQUE,
    -- seqName 保存号段中文名称，便于后台配置页面和运维排查时直接识别用途。
    seqName VARCHAR(128) NOT NULL,
    -- nextStartId 保存下一次成功抢号时可分配的起始主键值。
    nextStartId BIGINT NOT NULL,
    -- stepSize 保存每次成功抢号后分配给单个应用实例的号段长度。
    stepSize INT NOT NULL,
    -- versionNo 保存乐观锁版本号，供多个应用实例并发抢号时执行原子更新。
    versionNo INT NOT NULL DEFAULT 0,
    -- remark 保存号段补充说明，例如记录该号段对应的业务表和主键字段。
    remark VARCHAR(255),
    -- sortnum 保存号段配置的展示顺序，数值越小越靠前。
    sortnum DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    -- status 保存逻辑状态，1 表示有效，0 表示停用或逻辑删除。
    status INTEGER NOT NULL DEFAULT 1,
    -- createdAt 保存号段配置首次创建时间，便于审计初始化来源。
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- updatedAt 保存号段配置最后更新时间，便于确认最近维护时间。
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE CommonSequenceSegment IS '公共主键号段配置表';
COMMENT ON COLUMN CommonSequenceSegment.id IS '号段配置记录标识';
COMMENT ON COLUMN CommonSequenceSegment.tenantId IS '号段配置所属租户标识';
COMMENT ON COLUMN CommonSequenceSegment.lastOperateUserId IS '最近操作用户标识';
COMMENT ON COLUMN CommonSequenceSegment.seqCode IS '发号服务使用的唯一号段编码';
COMMENT ON COLUMN CommonSequenceSegment.seqName IS '号段中文名称';
COMMENT ON COLUMN CommonSequenceSegment.nextStartId IS '下一次分配的起始主键值';
COMMENT ON COLUMN CommonSequenceSegment.stepSize IS '单次分配给应用实例的号段长度';
COMMENT ON COLUMN CommonSequenceSegment.versionNo IS '并发抢号使用的乐观锁版本号';
COMMENT ON COLUMN CommonSequenceSegment.remark IS '号段用途和主键策略补充说明';
COMMENT ON COLUMN CommonSequenceSegment.sortnum IS '后台展示排序值';
COMMENT ON COLUMN CommonSequenceSegment.status IS '逻辑状态，1有效、0停用或删除';
COMMENT ON COLUMN CommonSequenceSegment.createdAt IS '数据创建时间';
COMMENT ON COLUMN CommonSequenceSegment.updatedAt IS '数据最后更新时间';

-- MdaConnectionProfile 保存页面维护的目标数据库连接配置；页面执行的 SQL 和目标库业务数据不会复制到 MDA 配置库。
CREATE TABLE IF NOT EXISTS MdaConnectionProfile (
    -- id 作为连接配置主键，由 CommonSequenceSegment 中的 MdaConnectionProfileId 号段统一生成。
    id BIGINT PRIMARY KEY,
    -- tenantId 表达连接配置所属租户，后续多租户场景可按该字段隔离各自可见连接。
    tenantId BIGINT NOT NULL,
    -- lastOperateUserId 记录最后新增、修改或删除该连接配置的用户标识。
    lastOperateUserId BIGINT NOT NULL,
    -- connectionName 保存页面左侧连接列表的显示名称，要求全局唯一以避免用户选错连接。
    connectionName VARCHAR(120) NOT NULL UNIQUE,
    -- databaseType 保存数据库类型，当前允许 H2、MYSQL、SQLSERVER、ORACLE、POSTGRESQL。
    databaseType VARCHAR(20) NOT NULL,
    -- host 保存目标数据库服务器主机名或 IP；H2 使用完整路径或自定义 URL 时可以为空。
    host VARCHAR(255),
    -- port 保存目标数据库监听端口；未填写时服务按数据库类型使用默认端口。
    port INTEGER,
    -- databaseName 保存数据库名称；H2 保存文件或内存库路径，Oracle 保存 service name。
    databaseName VARCHAR(240) NOT NULL,
    -- schemaName 保存连接后的默认 schema，页面浏览结构时可用于定位用户优先关注的模式。
    schemaName VARCHAR(120),
    -- username 保存连接目标数据库使用的登录账号，最终 SQL 权限由该数据库账号决定。
    username VARCHAR(120),
    -- passwordCiphertext 保存 AES/GCM 加密后的数据库口令，Service 解密后仅在建立 JDBC 连接时使用。
    passwordCiphertext VARCHAR(1000) NOT NULL DEFAULT '',
    -- customJdbcUrl 保存人工填写的完整 JDBC URL；存在时优先使用，不再根据 host、port 等字段自动拼接。
    customJdbcUrl VARCHAR(1000),
    -- jdbcParameters 保存自动拼接 JDBC URL 时追加的厂商参数，例如 useSSL=false 或 sslmode=disable。
    jdbcParameters VARCHAR(1000),
    -- defaultAutoCommit 保存该连接执行 SQL 时的默认自动提交设置，页面仍可在单次执行前覆盖。
    defaultAutoCommit BOOLEAN NOT NULL DEFAULT TRUE,
    -- sortnum 保存连接在页面左侧列表中的手工排序值，数值越小越靠前。
    sortnum DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    -- status 保存逻辑状态，1 表示页面可用，0 表示已逻辑删除且不再显示。
    status INTEGER NOT NULL DEFAULT 1,
    -- createdAt 保存连接配置首次创建时间，便于审计配置来源。
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- updatedAt 保存连接配置最后更新时间，便于判断配置是否近期发生变更。
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE MdaConnectionProfile IS 'MDA 目标数据库连接配置表';
COMMENT ON COLUMN MdaConnectionProfile.id IS '连接配置主键，由公共号段生成';
COMMENT ON COLUMN MdaConnectionProfile.tenantId IS '连接配置所属租户标识';
COMMENT ON COLUMN MdaConnectionProfile.lastOperateUserId IS '最近操作用户标识';
COMMENT ON COLUMN MdaConnectionProfile.connectionName IS '页面显示的唯一连接名称';
COMMENT ON COLUMN MdaConnectionProfile.databaseType IS '数据库类型：H2、MYSQL、SQLSERVER、ORACLE、POSTGRESQL';
COMMENT ON COLUMN MdaConnectionProfile.host IS '目标数据库服务器主机名或IP';
COMMENT ON COLUMN MdaConnectionProfile.port IS '目标数据库监听端口';
COMMENT ON COLUMN MdaConnectionProfile.databaseName IS '数据库名、H2路径或Oracle服务名';
COMMENT ON COLUMN MdaConnectionProfile.schemaName IS '连接后的默认Schema';
COMMENT ON COLUMN MdaConnectionProfile.username IS '目标数据库登录账号';
COMMENT ON COLUMN MdaConnectionProfile.passwordCiphertext IS 'AES/GCM加密连接口令，禁止返回页面';
COMMENT ON COLUMN MdaConnectionProfile.customJdbcUrl IS '优先使用的完整JDBC URL';
COMMENT ON COLUMN MdaConnectionProfile.jdbcParameters IS '自动拼接JDBC URL时追加的厂商参数';
COMMENT ON COLUMN MdaConnectionProfile.defaultAutoCommit IS 'SQL执行默认自动提交开关';
COMMENT ON COLUMN MdaConnectionProfile.sortnum IS '页面连接列表排序值';
COMMENT ON COLUMN MdaConnectionProfile.status IS '逻辑状态，1有效、0逻辑删除';
COMMENT ON COLUMN MdaConnectionProfile.createdAt IS '数据创建时间';
COMMENT ON COLUMN MdaConnectionProfile.updatedAt IS '数据最后更新时间';
