CREATE TABLE IF NOT EXISTS MdaModelCatalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelCode VARCHAR(64) NOT NULL UNIQUE,
    modelName VARCHAR(120) NOT NULL,
    modelType VARCHAR(32) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

MERGE INTO MdaModelCatalog KEY(modelCode) VALUES
    (1, 'user-profile', '用户档案模型', 'ENTITY', 1, CURRENT_TIMESTAMP),
    (2, 'reference-type', '引用数据类型模型', 'REFERENCE', 1, CURRENT_TIMESTAMP),
    (3, 'content-article', '内容文章模型', 'CONTENT', 1, CURRENT_TIMESTAMP);
